# Generated by Django 4.2.4 on 2023-11-24 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibo', '0002_unitplanerbasemodel_unitteacherroles_and_more'),
        ('myp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypreflectionpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='mypreflectionpost',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='mypreflectionpostidu',
            name='author',
        ),
        migrations.RemoveField(
            model_name='mypreflectionpostidu',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='mypunitplanner',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='mypunitplanner',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mypunitplanner',
            name='order',
        ),
        migrations.RemoveField(
            model_name='mypunitplanner',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='mypunitplanner',
            name='title',
        ),
        migrations.RemoveField(
            model_name='mypunitplanner',
            name='year',
        ),
        migrations.RemoveField(
            model_name='mypunitplannerinterdisciplinary',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='mypunitplannerinterdisciplinary',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mypunitplannerinterdisciplinary',
            name='title',
        ),
        migrations.RemoveField(
            model_name='mypunitplannerinterdisciplinary',
            name='year',
        ),
        migrations.AddField(
            model_name='mypunitplanner',
            name='unitplanerbasemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ibo.unitplanerbasemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypunitplannerinterdisciplinary',
            name='unitplanerbasemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ibo.unitplanerbasemodel'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MypProfileDevelop',
        ),
        migrations.DeleteModel(
            name='MypReflectionPost',
        ),
        migrations.DeleteModel(
            name='MypReflectionPostIdu',
        ),
    ]
