# Generated by Django 4.2.4 on 2023-11-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myp', '0002_remove_mypreflectionpost_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrandLevelAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True, verbose_name='Описание')),
                ('name_rus', models.TextField(blank=True, null=True, verbose_name='Описание на рус. языке')),
                ('point', models.PositiveIntegerField(default=0, verbose_name='Баллы')),
            ],
            options={
                'verbose_name': 'MYP: Уровень достижений',
                'verbose_name_plural': 'MYP: Уровни достижений',
                'ordering': ['level', 'point'],
            },
        ),
        migrations.RemoveField(
            model_name='achievementlevel',
            name='strand_level',
        ),
        migrations.RemoveField(
            model_name='educationallevel',
            name='years',
        ),
        migrations.AlterField(
            model_name='mypunitplanner',
            name='level',
            field=models.CharField(choices=[('a', 'Критерий A'), ('b', 'Критерий B'), ('c', 'Критерий C'), ('d', 'Критерий D')], max_length=12, null=True, verbose_name='Образовательный уровень'),
        ),
        migrations.AlterField(
            model_name='strandlevel',
            name='level',
            field=models.CharField(choices=[('a', 'Критерий A'), ('b', 'Критерий B'), ('c', 'Критерий C'), ('d', 'Критерий D')], max_length=12, null=True, verbose_name='Образовательный уровень'),
        ),
    ]
