# Generated by Django 4.2.4 on 2023-11-25 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_reportsecondarylevel_level'),
        ('myp', '0003_strandlevelachievement_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AchievementLevel',
        ),
        migrations.DeleteModel(
            name='EducationalLevel',
        ),
        migrations.AddField(
            model_name='strandlevelachievement',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achieve_levels', to='myp.strandlevel', verbose_name='Предметная цель'),
        ),
    ]
