# Generated by Django 4.2.4 on 2023-11-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibo', '0002_unitplanerbasemodel_unitteacherroles_and_more'),
        ('myp', '0004_delete_achievementlevel_delete_educationallevel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MypUnitPlannerInterdisciplinary',
            new_name='MypUnitPlannerId',
        ),
    ]
