# Generated by Django 4.2.4 on 2023-12-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myp', '0005_rename_mypunitplannerinterdisciplinary_mypunitplannerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strandlevel',
            name='level',
            field=models.CharField(choices=[('first', 'Year 1 / Emergent'), ('second', 'Year 3 / Capable'), ('third', 'Year 5 / Proficient'), ('None', 'Year All')], max_length=12, null=True, verbose_name='Образовательный уровень'),
        ),
    ]
