# Generated by Django 4.2.4 on 2023-12-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myp', '0006_alter_strandlevel_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strand',
            name='letter',
            field=models.PositiveIntegerField(choices=[(1, 'i'), (2, 'ii'), (3, 'iii'), (4, 'iv'), (5, 'v')], default=1, verbose_name='Метка в критерии'),
        ),
    ]
