# Generated by Django 4.2.4 on 2023-12-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myp', '0007_alter_strand_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strandlevel',
            name='level',
            field=models.PositiveIntegerField(choices=[(1, 'Year 1 / Emergent'), (3, 'Year 3 / Capable'), (5, 'Year 5 / Proficient'), (0, 'Year All')], default=0, null=True, verbose_name='Образовательный уровень'),
        ),
    ]
