# Generated by Django 4.2.4 on 2023-12-13 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibo', '0001_initial'),
        ('pyp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pypatldevelop',
            options={'ordering': ['unit', 'category', 'cluster', 'skill'], 'verbose_name': 'PYP: UnitPlan - Развитие ATL', 'verbose_name_plural': 'PYP: UnitPlans - Развитие ATL'},
        ),
        migrations.RenameField(
            model_name='pypatldevelop',
            old_name='atl',
            new_name='skill',
        ),
        migrations.AddField(
            model_name='pypatldevelop',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pyp_develops', to='ibo.atlcategory', verbose_name='Категория ATL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pypatldevelop',
            name='cluster',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='atl_develops', to='pyp.pypatlcluster', verbose_name='Кластер ATL'),
            preserve_default=False,
        ),
    ]
