# Generated by Django 4.2.4 on 2023-11-24 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibo', '0002_unitplanerbasemodel_unitteacherroles_and_more'),
        ('pyp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pypreflectionpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='pypreflectionpost',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='pypunitteacherroles',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='pypunitteacherroles',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pypunitplanner',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='pypunitplanner',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pypunitplanner',
            name='order',
        ),
        migrations.RemoveField(
            model_name='pypunitplanner',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='pypunitplanner',
            name='title',
        ),
        migrations.RemoveField(
            model_name='pypunitplanner',
            name='year',
        ),
        migrations.AddField(
            model_name='pypunitplanner',
            name='unitplanerbasemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ibo.unitplanerbasemodel'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PypProfileAttribute',
        ),
        migrations.DeleteModel(
            name='PypReflectionPost',
        ),
        migrations.DeleteModel(
            name='PypUnitTeacherRoles',
        ),
    ]
