# Generated by Django 4.2.4 on 2023-12-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pypkeyconcept',
            options={'ordering': ['name'], 'verbose_name': 'PYP: Ключевой концепт', 'verbose_name_plural': 'PYP: Ключевые концепты'},
        ),
    ]
