# Generated by Django 4.2.4 on 2023-11-19 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibo', '0001_initial'),
        ('pyp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pypatlskill',
            name='cluster',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pyp_skills', to='ibo.atlcluster', verbose_name='Кластер ATL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pypatlskill',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pyp_skills', to='pyp.pypatlgroup', verbose_name='Группа ATL'),
        ),
    ]
