# Generated by Django 4.2.4 on 2023-12-13 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyp', '0002_alter_pypatldevelop_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pypatldevelop',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atl_develops', to='pyp.pypatlcluster', verbose_name='Кластер ATL'),
        ),
        migrations.AlterField(
            model_name='pypatldevelop',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atl_develops', to='pyp.pypatlskill', verbose_name='Навык ATL'),
        ),
    ]
