# Generated by Django 4.2.4 on 2023-12-11 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibo', '0002_alter_unitplanerbasemodel_authors_and_more'),
        ('pyp', '0002_alter_pypkeyconcept_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pypatlskill',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='pyp.pypatlgroup', verbose_name='Группа ATL'),
        ),
        migrations.CreateModel(
            name='PypAtlCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('name_rus', models.CharField(blank=True, max_length=64, null=True, verbose_name='Название на рус. языке')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pyp_clusters', to='ibo.atlcategory', verbose_name='Категория ATL')),
            ],
            options={
                'verbose_name': 'IB: ATL кластер',
                'verbose_name_plural': 'IB: ATL кластеры',
                'ordering': ['category', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='pypatlgroup',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='pyp.pypatlcluster', verbose_name='Кластер ATL'),
        ),
        migrations.AlterField(
            model_name='pypatlskill',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='pyp.pypatlcluster', verbose_name='Кластер ATL'),
        ),
    ]
