# Generated by Django 4.2.4 on 2023-12-13 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyp', '0003_alter_pypatlskill_group_pypatlcluster_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pypatlcluster',
            options={'ordering': ['category', 'id'], 'verbose_name': 'PYP: ATL кластер', 'verbose_name_plural': 'PYP: ATL кластеры'},
        ),
    ]
