# Generated by Django 4.2.4 on 2023-12-16 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyp', '0003_alter_pypatldevelop_cluster_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pypunitplanner',
            old_name='conncetions',
            new_name='connections',
        ),
    ]
