# Generated by Django 4.2.4 on 2023-12-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название')),
                ('name_short', models.CharField(blank=True, max_length=32, null=True, verbose_name='Сокращённое название')),
                ('level', models.CharField(choices=[('noo', 'Начальная школа'), ('ooo', 'Средняя школа'), ('soo', 'Старшая школа'), ('None', 'Не указано')], default=None, max_length=4, verbose_name='Уровень образования')),
                ('ib', models.BooleanField(default=False, verbose_name='Наличие компонента IB')),
            ],
            options={
                'verbose_name': 'Учебный план',
                'verbose_name_plural': 'Учебные планы',
                'ordering': ['-year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('base', 'Обязательная часть'), ('base_fgos', 'Обязательная часть ФГОС в IB'), ('base_ib', 'Обязательная часть IB'), ('extra', 'Внеурочная деятельность'), ('None', 'Не выбрано')], default='base', max_length=10, verbose_name='Тип предмета')),
                ('hours', models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во часов')),
            ],
            options={
                'verbose_name': 'Учебный план - нагрузка',
                'verbose_name_plural': 'Учебные планы - нагрузка',
                'ordering': ['subject__name'],
            },
        ),
        migrations.CreateModel(
            name='FgosSubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('type', models.CharField(choices=[('area', 'Предметная область'), ('direction', 'Направление'), ('None', 'Не выбрано')], default='area', max_length=9, verbose_name='Тип группы')),
                ('level', models.CharField(choices=[('noo', 'Начальная школа'), ('ooo', 'Средняя школа'), ('soo', 'Старшая школа'), ('None', 'Не указано')], default=None, max_length=4, verbose_name='Уровень образования')),
            ],
            options={
                'verbose_name': 'Предметная группа ФГОС',
                'verbose_name_plural': 'Предметные группы ФГОС',
                'ordering': ['level', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IbDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название на англ. языке')),
                ('name_rus', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название на рус. языке')),
            ],
            options={
                'verbose_name': 'Специальная IB-дисциплина',
                'verbose_name_plural': 'Специальные IB-дисциплины',
                'ordering': ['group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IbSubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('name_rus', models.CharField(max_length=128, null=True, verbose_name='Название на рус. языке')),
                ('logo', models.ImageField(null=True, upload_to='subjectgroup_logos', verbose_name='Логотип')),
                ('program', models.CharField(choices=[('pyp', 'Primary Years Programme'), ('myp', 'Middle Years Programme'), ('dp', 'Diploma Programme'), ('None', 'No program')], default=None, max_length=4, null=True, verbose_name='Программа IB')),
            ],
            options={
                'verbose_name': 'Предметная группа IB',
                'verbose_name_plural': 'Предметные группы IB',
                'ordering': ['program', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('name_eng', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название на англ. языке')),
                ('dnevnik_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='ID системы Дневник.РУ')),
                ('level', models.CharField(choices=[('noo', 'Начальная школа'), ('ooo', 'Средняя школа'), ('soo', 'Старшая школа'), ('None', 'Не указано')], default=None, max_length=4, verbose_name='Уровень образования')),
                ('need_report', models.BooleanField(default=False, verbose_name='Необходимость репорта')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeachingLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveSmallIntegerField(default=1, verbose_name='Часы')),
            ],
            options={
                'verbose_name': 'Рабочая нагрузка учителя',
                'verbose_name_plural': 'Рабочие нагрузки учителей ',
                'ordering': ['year', 'subject', 'teacher'],
            },
        ),
    ]
