# Generated by Django 4.2.4 on 2023-11-20 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('general', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingload',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='teaching_loads', to='general.classgroup', verbose_name='Классы'),
        ),
        migrations.AddField(
            model_name='teachingload',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_loads', to='curriculum.subject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='teachingload',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_loads', to=settings.AUTH_USER_MODEL, verbose_name='Учитель'),
        ),
        migrations.AddField(
            model_name='teachingload',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_loads', to='general.academicyear', verbose_name='Учебный год'),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='general.department', verbose_name='Учебное подразделение'),
        ),
        migrations.AddField(
            model_name='subject',
            name='group_fgos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='curriculum.fgossubjectgroup', verbose_name='Предметная область в РФ'),
        ),
        migrations.AddField(
            model_name='subject',
            name='group_ib',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='curriculum.ibsubjectgroup', verbose_name='Предметная группа в IB'),
        ),
        migrations.AddField(
            model_name='ibdiscipline',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specific_disciplines', to='curriculum.ibsubjectgroup', verbose_name='Предметная группа'),
        ),
        migrations.AddField(
            model_name='curriculumload',
            name='curriculum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_loads', to='curriculum.curriculum', verbose_name='Учебный план'),
        ),
        migrations.AddField(
            model_name='curriculumload',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_loads', to='curriculum.subject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='curriculumload',
            name='years',
            field=models.ManyToManyField(related_name='curriculum_loads', to='general.studyyear', verbose_name='Параллель'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to='general.academicyear', verbose_name='Учебный год'),
        ),
    ]
