# Generated by Django 4.2.4 on 2023-12-20 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0001_initial'),
        ('curriculum', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingload',
            name='groups',
            field=models.ManyToManyField(related_name='teaching_loads', to='general.classgroup', verbose_name='Классы'),
        ),
        migrations.AlterField(
            model_name='teachingload',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_loads', to='curriculum.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='teachingload',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_loads', to=settings.AUTH_USER_MODEL, verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='teachingload',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_loads', to='general.academicyear', verbose_name='Учебный год'),
        ),
    ]
