# Generated by Django 4.2.4 on 2023-11-22 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='discipline_ib',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='curriculum.ibdiscipline', verbose_name='Дисциплина в IB'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='dnevnik_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='ID системы Дневник.РУ'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='group_fgos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='curriculum.fgossubjectgroup', verbose_name='Предметная область в РФ'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='group_ib',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='curriculum.ibsubjectgroup', verbose_name='Предметная группа в IB'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name_eng',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Название на англ. языке'),
        ),
    ]
