# Generated by Django 4.2.4 on 2023-11-19 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        ('curriculum', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to='general.academicyear', verbose_name='Учебный год'),
        ),
    ]
