# Generated by Django 4.2.4 on 2023-11-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_alter_subject_discipline_ib_alter_subject_dnevnik_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='ib',
            field=models.BooleanField(default=False, verbose_name='Наличие компонента IB'),
        ),
    ]
