version: '3.8'

services:
  database:
    container_name: database
    image: postgres:14.0-alpine
    networks:
      - main
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env/.env.db

  redis:
    container_name: redis
    image: redis:6
    networks:
      - main

  celery:
    container_name: celery
    build:
      dockerfile: ./docker/product/backend/Dockerfile
    command: celery -A config worker --loglevel=info
    networks:
      - main
    env_file:
      - ./backend/.env/.env.prod
    depends_on:
      - database
      - backend
      - redis
  
  celery-beat:
    container_name: celery-beat
    build:
      dockerfile: ./docker/product/backend/Dockerfile
    command: celery -A config beat --loglevel=info
    networks:
      - main
    depends_on:
      - backend
      - redis

  backend:
    container_name: backend
    build:
      dockerfile: ./docker/product/backend/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - main
    depends_on:
      - database
      - redis
    env_file:
      - ./backend/.env/.env.prod

  frontend:
    container_name: frontend
    build:
      dockerfile: ./docker/product/frontend/Dockerfile
    networks:
      - main
    ports:
      - "80:80"
      - "443:443"
    
volumes:
  postgres_data:

networks:
  main:
    driver: bridge

