version: '3.8'

services:
  database:
    container_name: database
    image: postgres:14.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env/.env.db

  redis:
    container_name: redis
    image: redis:6

  celery:
    container_name: celery
    build:
      dockerfile: ./docker/product/backend/Dockerfile
    command: celery -A config worker --loglevel=info
    env_file:
      - ./backend/.env/.env.prod
    depends_on:
      - database
      - backend
      - redis
  
  celery-beat:
    container_name: celery-beat
    build:
      dockerfile: ./docker/product/backend/Dockerfile
    command: celery -A config beat --loglevel=info
    depends_on:
      - backend
      - redis

  backend:
    container_name: backend
    build:
      dockerfile: ./docker/product/backend/Dockerfile
    volumes:
      - static:/home/app/backend/staticfiles
      - media:/home/app/backend/mediafiles
    ports:
      - "8000:8000"
    depends_on:
      - database
      - redis
    env_file:
      - ./backend/.env/.env.prod

  frontend:
    container_name: frontend
    build:
      dockerfile: ./docker/product/frontend/Dockerfile
    volumes:
      - static:/home/app/backend/staticfiles
      - media:/home/app/backend/mediafiles
    ports:
      - "80:80"
      - "443:443"
    
volumes:
  postgres_data:
  static:
  media:

