version: '3.8'

services:
  database:
    image: postgres:14.0-alpine
    container_name: database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=igskolkovo
    ports:
      - 54320:5432
    networks:
      - main

  redis:
    image: redis:6
    networks:
      - main

  celery:
    build:
      dockerfile: ./docker/develop/backend/Dockerfile
    command: celery -A config worker --loglevel=info
    volumes:
      - ./backend/:/backend
    env_file:
      - ./backend/.env/.env
    networks:
      - main
    depends_on:
      - database
      - backend
      - redis
  
  celery-beat:
    build:
      dockerfile: ./docker/develop/backend/Dockerfile
    command: celery -A config beat --loglevel=info
    volumes:
      - ./backend/:/backend
    networks:
      - main
    depends_on:
      - backend
      - redis

  backend:
    container_name: develop-backend
    build:
      dockerfile: ./docker/develop/backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/backend
    depends_on:
      - database
      - redis
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env/.env
    networks:
      - main

  frontend:
    build:
      dockerfile: ./docker/develop/frontend/Dockerfile
    container_name: develop-frontend
    command: sh -c "npm rebuild esbuild && npm run dev -- --host"
    volumes:
      - ./frontend:/frontend/
    environment:
      PORT: '8080'
      HOST: '0.0.0.0'
    ports:
      - '8080:8080'
    networks:
      - main

volumes:
  postgres_data:

networks:
  main:
    driver: bridge