version: "3.6"
services:
  frontend:
    container_name: igskolkovo-frontend
    image: index.docker.io/aleksioprime/igskolkovo-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - main
  backend:
    container_name: igskolkovo-backend
    image: index.docker.io/aleksioprime/igskolkovo-backend
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - POSTGRES_DB=igskolkovo
      - POSTGRES_USER=igadmin
      - POSTGRES_PASSWORD=Pox{@K
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - main
  postgres:
    container_name: postgres
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=igadmin
      - POSTGRES_PASSWORD=Pox{@K
      - POSTGRES_DB=igskolkovo
    ports:
      - "5432:5432"
    networks:
      - main
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
volumes:
  postgres_data:
networks:
  main:
    driver: bridge
