# Generated by Django 4.2.4 on 2023-11-19 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        ('units', '0002_alter_mypinquiryquestionidu_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetopic',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dp_topics', to='curriculum.ibdiscipline', verbose_name='Discipline IB'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dp_criteria', to='curriculum.ibdiscipline', verbose_name='Discipline IB'),
        ),
        migrations.AlterField(
            model_name='dpaim',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dp_aims', to='curriculum.ibdiscipline', verbose_name='Discipline IB'),
        ),
        migrations.AlterField(
            model_name='dpobjective',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dp_objectives', to='curriculum.ibdiscipline', verbose_name='Discipline IB'),
        ),
        migrations.AlterField(
            model_name='dpunitplanner',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dp_unitplans', to='curriculum.subject', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='mypaim',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myp_aims', to='curriculum.ibsubjectgroup', verbose_name='Предметная группа'),
        ),
        migrations.AlterField(
            model_name='mypkeyconcept',
            name='groups',
            field=models.ManyToManyField(related_name='key_concepts', through='units.MypKeyConceptOfSubjects', to='curriculum.ibsubjectgroup', verbose_name='Рекомендуемые предметные группы'),
        ),
        migrations.AlterField(
            model_name='mypkeyconceptofsubjects',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_concepts_recomends', to='curriculum.ibsubjectgroup', verbose_name='Предметная группа'),
        ),
        migrations.AlterField(
            model_name='mypobjective',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myp_objectives', to='curriculum.ibsubjectgroup', verbose_name='Предметная группа IB'),
        ),
        migrations.AlterField(
            model_name='myprelatedconcept',
            name='disciplines',
            field=models.ManyToManyField(related_name='related_concepts', to='curriculum.ibdiscipline', verbose_name='Специальные дисциплины'),
        ),
        migrations.AlterField(
            model_name='mypunitplanner',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myp_unitplans', to='curriculum.subject', verbose_name='Предмет'),
        ),
    ]
