# Generated by Django 4.2.4 on 2023-11-20 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myp', '0001_initial'),
        ('curriculum', '0002_initial'),
        ('general', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pyp', '0001_initial'),
        ('syllabus', '0001_initial'),
        ('ibo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Номер периода')),
                ('name', models.CharField(default=None, max_length=128, null=True, verbose_name='Название периода')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_period', to='general.academicyear', verbose_name='Учебный год')),
            ],
            options={
                'verbose_name': 'Период репортов',
                'verbose_name_plural': 'Периоды репортов',
                'ordering': ['year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ReportSecondaryCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.SmallIntegerField(default=None, null=True, verbose_name='Балл')),
                ('criterion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mark_reports', to='myp.mypobjective', verbose_name='Критерий')),
            ],
            options={
                'verbose_name': 'Репорты средней школы: баллы по критериям',
                'verbose_name_plural': 'Репорты средней школы: баллы по критериям',
                'ordering': ['report', 'criterion'],
            },
        ),
        migrations.CreateModel(
            name='ReportTeacherSecondary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Текст репорта')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменён')),
                ('final_grade', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Итоговая оценка')),
                ('achievements', models.ManyToManyField(blank=True, related_name='reports', to='myp.achievementlevel', verbose_name='Уровни достижений')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_author_reports', to=settings.AUTH_USER_MODEL, verbose_name='Автор репорта')),
                ('criteria', models.ManyToManyField(blank=True, related_name='reports', through='report.ReportSecondaryCriteria', to='myp.mypobjective', verbose_name='Критерии ')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reports', to='general.classgroup', verbose_name='Класс')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reports', to='report.reportperiod', verbose_name='Период репорта')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_student_reports', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reports', to='curriculum.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Репорт средней школы',
                'verbose_name_plural': 'Репорты средней школы',
            },
        ),
        migrations.CreateModel(
            name='ReportTeacherPrimary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Текст репорта')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменён')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_author_reports', to=settings.AUTH_USER_MODEL, verbose_name='Автор репорта')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reports', to='general.classgroup', verbose_name='Класс')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reports', to='report.reportperiod', verbose_name='Период репорта')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_student_reports', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reports', to='curriculum.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Репорт начальной школы',
                'verbose_name_plural': 'Репорты начальной школы',
            },
        ),
        migrations.CreateModel(
            name='ReportTeacherHigh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Текст репорта')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменён')),
                ('final_grade', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Итоговая оценка (2-5)')),
                ('final_grade_ib', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Итоговая оценка (1-7)')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_author_reports', to=settings.AUTH_USER_MODEL, verbose_name='Автор репорта')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reports', to='general.classgroup', verbose_name='Класс')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reports', to='report.reportperiod', verbose_name='Период репорта')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_student_reports', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reports', to='curriculum.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Репорт старшей школы',
                'verbose_name_plural': 'Репорты старшей школы',
            },
        ),
        migrations.AddField(
            model_name='reportsecondarycriteria',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mark_criteria', to='report.reportteachersecondary', verbose_name='Репорт'),
        ),
        migrations.CreateModel(
            name='ReportPrimaryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='report.reportteacherprimary', verbose_name='Репорт')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='pyp.pypunitplanner', verbose_name='Юнит')),
            ],
            options={
                'verbose_name': 'Репорты начальной школы: юнит',
                'verbose_name_plural': 'Репорты начальной школы: юниты',
                'ordering': ['report', 'unit'],
            },
        ),
        migrations.CreateModel(
            name='ReportPrimaryIbProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('low', 'Слегка выражено'), ('medium', 'Выражено'), ('high', 'Выражено в сильной степени'), ('None', 'Не указан')], default=None, max_length=6, verbose_name='Уровень')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='ibo.learnerprofile', verbose_name='Профиль студента')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='report.reportteacherprimary', verbose_name='Репорт')),
            ],
            options={
                'verbose_name': 'Репорты начальной школы: профили студента IB',
                'verbose_name_plural': 'Репорты начальной школы: профиль студента IB',
                'ordering': ['report', 'profile'],
            },
        ),
        migrations.CreateModel(
            name='ReportPrimaryAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A', 'Уровень A'), ('B', 'Уровень B'), ('C', 'Уровень C'), ('None', 'Не указан')], default=None, max_length=4, verbose_name='Уровень')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='report.reportteacherprimary', verbose_name='Репорт')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='syllabus.coursetopic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Репорты начальной школы: академические достижения',
                'verbose_name_plural': 'Репорты начальной школы: академические достижения',
                'ordering': ['report', 'topic'],
            },
        ),
        migrations.CreateModel(
            name='ReportMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Текст репорта')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменён')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_author_reports', to=settings.AUTH_USER_MODEL, verbose_name='Автор репорта')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reports', to='general.classgroup', verbose_name='Класс')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reports', to='report.reportperiod', verbose_name='Период репорта')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_student_reports', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Репорт наставника',
                'verbose_name_plural': 'Репорты наставника',
            },
        ),
        migrations.CreateModel(
            name='ReportExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Текст репорта')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменён')),
                ('role', models.CharField(default=None, max_length=255, null=True, verbose_name='Укажите свою роль')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_author_reports', to=settings.AUTH_USER_MODEL, verbose_name='Автор репорта')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reports', to='general.classgroup', verbose_name='Класс')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reports', to='report.reportperiod', verbose_name='Период репорта')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_student_reports', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Репорт службы сопрождения',
                'verbose_name_plural': 'Репорты службы сопровождения',
            },
        ),
    ]
