# Generated by Django 4.2.4 on 2023-12-13 18:32

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ibo', '0001_initial'),
        ('general', '0001_initial'),
        ('pyp', '0001_initial'),
        ('curriculum', '0002_initial'),
        ('syllabus', '0001_initial'),
        ('myp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=128, null=True, verbose_name='Название критерия')),
                ('type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('teacher', 'Репорты учителя'), ('mentor', 'Репорты наставника'), ('extra', 'Репорты службы сопровождения')], max_length=7), blank=True, default=list, size=None, verbose_name='Тип репорта')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_criteria', to=settings.AUTH_USER_MODEL, verbose_name='Автор критерия')),
                ('subjects', models.ManyToManyField(blank=True, related_name='report_criteria', to='curriculum.subject', verbose_name='Предметы')),
                ('years', models.ManyToManyField(related_name='report_criteria', to='general.studyyear', verbose_name='Параллели')),
            ],
            options={
                'verbose_name': 'Критерий для репорта',
                'verbose_name_plural': 'Критерии для репорта',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Текст репорта')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменён')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_author_reports', to=settings.AUTH_USER_MODEL, verbose_name='Автор репорта')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reports', to='general.classgroup', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Репорт наставника',
                'verbose_name_plural': 'Репорты наставника',
            },
        ),
        migrations.CreateModel(
            name='ReportPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Номер периода')),
                ('name', models.CharField(default=None, max_length=128, null=True, verbose_name='Название периода')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_period', to='general.academicyear', verbose_name='Учебный год')),
            ],
            options={
                'verbose_name': 'Период репортов',
                'verbose_name_plural': 'Периоды репортов',
                'ordering': ['year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ReportTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Текст репорта')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменён')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_author_reports', to=settings.AUTH_USER_MODEL, verbose_name='Автор репорта')),
                ('extra_subjects', models.ManyToManyField(blank=True, related_name='extra_reports', to='curriculum.subject', verbose_name='Дополнительные предметы')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reports', to='general.classgroup', verbose_name='Класс')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reports', to='report.reportperiod', verbose_name='Период репорта')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_student_reports', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='curriculum.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Репорт учителя',
                'verbose_name_plural': 'Репорты учителя',
                'ordering': ['period', 'subject', 'student', 'author'],
            },
        ),
        migrations.CreateModel(
            name='ReportMentorPrimary',
            fields=[
                ('reportmentor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report.reportmentor')),
            ],
            options={
                'verbose_name': 'Репорт наставника НШ',
                'verbose_name_plural': 'Репорты наставника НШ',
            },
            bases=('report.reportmentor',),
        ),
        migrations.CreateModel(
            name='ReportTeacherHigh',
            fields=[
                ('reportteacher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report.reportteacher')),
                ('final_grade', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Итоговая оценка (2-5)')),
                ('final_grade_ib', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Итоговая оценка (1-7)')),
            ],
            options={
                'verbose_name': 'Репорт учителя СтШ',
                'verbose_name_plural': 'Репорты учителя СтШ',
            },
            bases=('report.reportteacher',),
        ),
        migrations.CreateModel(
            name='ReportTeacherPrimary',
            fields=[
                ('reportteacher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report.reportteacher')),
            ],
            options={
                'verbose_name': 'Репорт учителя НШ',
                'verbose_name_plural': 'Репорты учителя НШ',
            },
            bases=('report.reportteacher',),
        ),
        migrations.CreateModel(
            name='ReportTeacherSecondary',
            fields=[
                ('reportteacher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report.reportteacher')),
                ('final_grade', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Итоговая оценка')),
            ],
            options={
                'verbose_name': 'Репорт учителя СрШ',
                'verbose_name_plural': 'Репорты учителя СрШ',
            },
            bases=('report.reportteacher',),
        ),
        migrations.AddField(
            model_name='reportmentor',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reports', to='report.reportperiod', verbose_name='Период репорта'),
        ),
        migrations.AddField(
            model_name='reportmentor',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_student_reports', to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.CreateModel(
            name='ReportIbProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, choices=[('low', 'Слегка выражено'), ('medium', 'Выражено'), ('high', 'Выражено в сильной степени'), ('None', 'Не указан')], default=None, max_length=6, null=True, verbose_name='Уровень')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='ibo.learnerprofile', verbose_name='Профиль студента')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='report.reportmentor', verbose_name='Репорт наставника')),
            ],
            options={
                'verbose_name': 'Репорты наставника: профили студента IB',
                'verbose_name_plural': 'Репорты наставника: профиль студента IB',
                'ordering': ['report', 'profile'],
            },
        ),
        migrations.CreateModel(
            name='ReportExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Текст репорта')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменён')),
                ('role', models.CharField(default=None, max_length=255, null=True, verbose_name='Укажите свою роль')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_author_reports', to=settings.AUTH_USER_MODEL, verbose_name='Автор репорта')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reports', to='general.classgroup', verbose_name='Класс')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reports', to='report.reportperiod', verbose_name='Период репорта')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_student_reports', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Репорт службы сопрождения',
                'verbose_name_plural': 'Репорты службы сопровождения',
            },
        ),
        migrations.CreateModel(
            name='ReportCriterionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=128, null=True, verbose_name='Название уровня')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание результата')),
                ('point', models.PositiveSmallIntegerField(default=1, verbose_name='Баллы')),
                ('criterion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='report.reportcriterion', verbose_name='Критерий')),
            ],
            options={
                'verbose_name': 'Критерий для репорта: уровень',
                'verbose_name_plural': 'Критерий для репорта: уровни',
                'ordering': ['point', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportCriterionAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='report.reportcriterionlevel', verbose_name='Достижение по критерию')),
                ('criterion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='report.reportcriterion', verbose_name='Чеклист')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterion_achievements', to='report.reportteacher', verbose_name='Репорт учителя')),
                ('report_extra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterion_achievements', to='report.reportextra', verbose_name='Репорт службы сопровождения')),
                ('report_mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterion_achievements', to='report.reportmentor', verbose_name='Репорт наставника')),
            ],
            options={
                'verbose_name': 'Репорты: достижение по критерию',
                'verbose_name_plural': 'Репорты: достижения по критериям',
            },
        ),
        migrations.CreateModel(
            name='ReportSecondaryLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_levels', to='myp.strandlevelachievement', verbose_name='Уровень достижений')),
                ('strand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_levels', to='myp.strandlevel', verbose_name='Предметная цель')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objective_levels', to='report.reportteachersecondary', verbose_name='Репорт')),
            ],
            options={
                'verbose_name': 'Репорты учителя СрШ: уровнень достижений',
                'verbose_name_plural': 'Репорты учителя СрШ: уровни достижений',
                'ordering': ['strand'],
            },
        ),
        migrations.CreateModel(
            name='ReportSecondaryCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.SmallIntegerField(default=None, null=True, verbose_name='Балл')),
                ('criterion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criterion_marks', to='myp.mypobjective', verbose_name='Критерий')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterion_marks', to='report.reportteachersecondary', verbose_name='Репорт')),
            ],
            options={
                'verbose_name': 'Репорты учителя СрШ: баллы по критериям',
                'verbose_name_plural': 'Репорты учителя СрШ: баллы по критериям',
                'ordering': ['report', 'criterion'],
            },
        ),
        migrations.CreateModel(
            name='ReportPrimaryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pyp_reports', to='pyp.pypunitplanner', verbose_name='Юнит')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pyp_units', to='report.reportmentorprimary', verbose_name='Репорт наставника НШ')),
            ],
            options={
                'verbose_name': 'Репорты наставника НШ: юнит PYP',
                'verbose_name_plural': 'Репорты наставника НШ: юниты PYP',
                'ordering': ['report', 'unit'],
            },
        ),
        migrations.CreateModel(
            name='ReportPrimaryTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.TextField(blank=True, null=True, verbose_name='Тема (дополнительное текстовое поле)')),
                ('level', models.CharField(choices=[('a', 'Уровень A'), ('b', 'Уровень B'), ('c', 'Уровень C'), ('None', 'Не указан')], default=None, max_length=4, null=True, verbose_name='Уровень')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_achievements', to='syllabus.coursetopic', verbose_name='Тема')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_achievements', to='report.reportteacherprimary', verbose_name='Репорт')),
            ],
            options={
                'verbose_name': 'Репорты учителя НШ: академические достижения',
                'verbose_name_plural': 'Репорты учителя НШ: академические достижения',
                'ordering': ['report', 'topic'],
            },
        ),
    ]
