# Generated by Django 4.2.4 on 2023-11-19 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportprimaryachievement',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='syllabus.coursetopic', verbose_name='Тема'),
        ),
    ]
