# Generated by Django 4.2.4 on 2023-12-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcriterionlevel',
            name='recommendations',
            field=models.TextField(blank=True, null=True, verbose_name='Рекомендации'),
        ),
        migrations.AlterField(
            model_name='reportcriterion',
            name='name',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name='Название критерия'),
        ),
    ]
