# Generated by Django 4.2.4 on 2023-11-22 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
        ('myp', '0001_initial'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSecondaryLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objective_levels', to='myp.achievementlevel', verbose_name='Уровень достижений')),
                ('objective', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objective_levels', to='myp.mypobjective', verbose_name='Предметная цель')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objective_levels', to='report.reportteachersecondary', verbose_name='Репорт')),
            ],
            options={
                'verbose_name': 'Репорты учителя СрШ: уровнень достижений',
                'verbose_name_plural': 'Репорты учителя СрШ: уровни достижений',
                'ordering': ['objective'],
            },
        ),
        migrations.AlterField(
            model_name='reportprimaryachievement',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_achievements', to='report.reportteacherprimary', verbose_name='Репорт'),
        ),
        migrations.AlterField(
            model_name='reportprimaryachievement',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_achievements', to='syllabus.coursetopic', verbose_name='Тема'),
        ),
        migrations.DeleteModel(
            name='ReportSecondaryAchievement',
        ),
    ]
