# Generated by Django 4.2.4 on 2023-12-03 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myp', '0001_initial'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportsecondarylevel',
            options={'ordering': ['strand'], 'verbose_name': 'Репорты учителя СрШ: уровнень достижений', 'verbose_name_plural': 'Репорты учителя СрШ: уровни достижений'},
        ),
        migrations.RemoveField(
            model_name='reportsecondarylevel',
            name='objective',
        ),
        migrations.AddField(
            model_name='reportsecondarylevel',
            name='strand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_levels', to='myp.strandlevel', verbose_name='Предметная цель'),
        ),
        migrations.AlterField(
            model_name='reportsecondarylevel',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_levels', to='myp.strandlevelachievement', verbose_name='Уровень достижений'),
        ),
    ]
