# Generated by Django 4.2.4 on 2023-11-19 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyp', '0002_pypatlskill_cluster_alter_pypatlskill_group'),
        ('report', '0002_alter_reportprimaryachievement_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPrimaryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_units', to='report.reportteacherprimary', verbose_name='Репорт')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_reports', to='pyp.pypunitplanner', verbose_name='Юнит')),
            ],
            options={
                'verbose_name': 'Репорты начальной школы: юнит',
                'verbose_name_plural': 'Репорты начальной школы: юниты',
                'ordering': ['report', 'unit'],
            },
        ),
        migrations.AddField(
            model_name='reportteacherprimary',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='reports', through='report.ReportPrimaryUnit', to='pyp.pypunitplanner', verbose_name='Юниты '),
        ),
    ]
