# Generated by Django 4.2.4 on 2023-11-23 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
        ('pyp', '0001_initial'),
        ('report', '0002_reportsecondarylevel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportPrimaryAchievement',
            new_name='ReportPrimaryTopic',
        ),
        migrations.AlterField(
            model_name='reportprimaryunit',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pyp_reports', to='pyp.pypunitplanner', verbose_name='Юнит'),
        ),
    ]
