# Generated by Django 4.2.4 on 2023-12-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_reportcriterionlevel_recommendations_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportcriterionachievement',
            options={'ordering': ['criterion'], 'verbose_name': 'Репорты: достижение по критерию', 'verbose_name_plural': 'Репорты: достижения по критериям'},
        ),
    ]
