# Generated by Django 4.2.4 on 2023-12-08 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_initial'),
        ('report', '0002_alter_reportsecondarylevel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportcriterionachievement',
            options={'verbose_name': 'Репорты: достижение по критерию', 'verbose_name_plural': 'Репорты: достижения по критериям'},
        ),
        migrations.AddField(
            model_name='reportteacher',
            name='extra_subjects',
            field=models.ManyToManyField(blank=True, related_name='extra_reports', to='curriculum.subject', verbose_name='Дополнительные предметы'),
        ),
        migrations.AlterField(
            model_name='reportcriterionachievement',
            name='achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='report.reportcriterionlevel', verbose_name='Достижение по критерию'),
        ),
    ]
