# Generated by Django 4.2.4 on 2023-12-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_reportcriterionachievement_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcriterion',
            name='name_eng',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Название критерия на английском'),
        ),
    ]
