# Generated by Django 4.2.4 on 2023-11-20 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyp', '0002_pypatlskill_cluster_alter_pypatlskill_group'),
        ('report', '0003_reportprimaryunit_reportteacherprimary_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportteacherprimary',
            name='units',
        ),
        migrations.AlterField(
            model_name='reportprimaryunit',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='report.reportteacherprimary', verbose_name='Репорт'),
        ),
        migrations.AlterField(
            model_name='reportprimaryunit',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='pyp.pypunitplanner', verbose_name='Юнит'),
        ),
    ]
