# Generated by Django 4.2.4 on 2023-11-25 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myp', '0003_strandlevelachievement_and_more'),
        ('report', '0003_rename_reportprimaryachievement_reportprimarytopic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsecondarylevel',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objective_levels', to='myp.strandlevelachievement', verbose_name='Уровень достижений'),
        ),
    ]
