# Generated by Django 4.2.4 on 2023-12-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_reportcriterionachievement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportprimarytopic',
            name='topic_name',
            field=models.TextField(blank=True, null=True, verbose_name='Тема (дополнительное текстовое поле)'),
        ),
    ]
