# Generated by Django 4.2.4 on 2023-12-13 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_reportprimarytopic_topic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportcriterion',
            name='levels',
        ),
        migrations.AddField(
            model_name='reportcriterionachievement',
            name='report_mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterion_achievements', to='report.reportmentor', verbose_name='Репорт наставника'),
        ),
    ]
