# Generated by Django 4.2.4 on 2023-11-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_reportsecondarylevel_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportprimarytopic',
            name='level',
            field=models.CharField(choices=[('A', 'Уровень A'), ('B', 'Уровень B'), ('C', 'Уровень C'), ('None', 'Не указан')], default=None, max_length=4, null=True, verbose_name='Уровень'),
        ),
    ]
