# Generated by Django 4.2.4 on 2023-12-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_reportcriterion_name_eng'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcriterionlevel',
            name='description_eng',
            field=models.TextField(blank=True, null=True, verbose_name='Описание результата на английском языке'),
        ),
        migrations.AddField(
            model_name='reportcriterionlevel',
            name='name_eng',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Название уровня на английском языке'),
        ),
    ]
