# Generated by Django 4.2.4 on 2023-12-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_reportprimarytopic_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportprimarytopic',
            name='level',
            field=models.CharField(choices=[('a', 'Уровень A'), ('b', 'Уровень B'), ('c', 'Уровень C'), ('None', 'Не указан')], default=None, max_length=4, null=True, verbose_name='Уровень'),
        ),
    ]
