# Generated by Django 4.2.4 on 2023-12-13 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_remove_reportcriterion_levels_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCriterionLevelDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание результата')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='report.reportcriterion', verbose_name='Критерий')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='report.reportcriterionlevel', verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Критерий для репорта учителя: уровень',
                'verbose_name_plural': 'Критерий для репорта учителя: уровни',
                'ordering': ['criterion', 'level'],
            },
        ),
        migrations.AddField(
            model_name='reportcriterion',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='criterions', through='report.ReportCriterionLevelDescription', to='report.reportcriterionlevel', verbose_name='Уровни достижений'),
        ),
    ]
