# Generated by Django 4.2.4 on 2024-01-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_reportcriterionlevel_description_eng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportperiod',
            name='name_eng',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='Название периода на англ. языке'),
        ),
    ]
