# Generated by Django 4.2.4 on 2023-12-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_alter_reportprimarytopic_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportcriterion',
            options={'ordering': ['name'], 'verbose_name': 'Критерий для репорта учителя', 'verbose_name_plural': 'Критерии для репорта учителя'},
        ),
        migrations.AlterModelOptions(
            name='reportcriterionlevel',
            options={'ordering': ['point', 'name'], 'verbose_name': 'Критерий для репорта учителя: уровень', 'verbose_name_plural': 'Критерий для репорта учителя: уровни'},
        ),
        migrations.RemoveField(
            model_name='reportcriterionlevel',
            name='criterion',
        ),
        migrations.AddField(
            model_name='reportcriterion',
            name='levels',
            field=models.ManyToManyField(null=True, related_name='criterions', to='report.reportcriterionlevel', verbose_name='Уровни достижений'),
        ),
    ]
