# Generated by Django 4.2.4 on 2023-12-13 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_reportcriterionleveldescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcriterionachievement',
            name='report_extra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterion_achievements', to='report.reportextra', verbose_name='Репорт службы сопровождения'),
        ),
    ]
