# Generated by Django 4.2.4 on 2023-12-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_alter_reportcriterion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcriterion',
            name='levels',
            field=models.ManyToManyField(blank=True, null=True, related_name='criterions', to='report.reportcriterionlevel', verbose_name='Уровни достижений'),
        ),
        migrations.AlterField(
            model_name='reportcriterionlevel',
            name='name',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='Название уровня'),
        ),
        migrations.AlterField(
            model_name='reportibprofile',
            name='level',
            field=models.CharField(blank=True, choices=[('low', 'Слегка выражено'), ('medium', 'Выражено'), ('high', 'Выражено в сильной степени'), ('None', 'Не указан')], default=None, max_length=6, null=True, verbose_name='Уровень'),
        ),
    ]
