# Generated by Django 4.2.4 on 2023-12-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_alter_reportcriterion_levels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcriterion',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='criterions', to='report.reportcriterionlevel', verbose_name='Уровни достижений'),
        ),
    ]
