# Generated by Django 4.2.4 on 2023-12-02 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_alter_reportcriterion_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportmentorprimary',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reportmentorprimary',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='reportmentorprimary',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reportmentorprimary',
            name='group',
        ),
        migrations.RemoveField(
            model_name='reportmentorprimary',
            name='id',
        ),
        migrations.RemoveField(
            model_name='reportmentorprimary',
            name='period',
        ),
        migrations.RemoveField(
            model_name='reportmentorprimary',
            name='student',
        ),
        migrations.RemoveField(
            model_name='reportmentorprimary',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='reportmentorprimary',
            name='reportmentor_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report.reportmentor'),
            preserve_default=False,
        ),
    ]
