version: '3.8'

services:
  database:
    container_name: database
    image: postgres:14.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env/.env.db

  redis:
    container_name: redis
    image: redis:6

  celery:
    container_name: celery
    image: index.docker.io/aleksioprime/streamreport_backend
    command: celery -A config worker --loglevel=info
    env_file:
      - .env/.env.prod
    depends_on:
      - database
      - backend
      - redis

  celery-beat:
    container_name: celery-beat
    image: index.docker.io/aleksioprime/streamreport_backend
    command: celery -A config beat --loglevel=info
    depends_on:
      - backend
      - redis

  backend:
    container_name: backend
    image: index.docker.io/aleksioprime/streamreport_backend
    volumes:
      - ./static:/home/app/backend/staticfiles
      - ./media:/home/app/backend/mediafiles\
    ports:
      - "8000:8000"
    depends_on:
      - database
      - redis
    env_file:
      - .env/.env.prod

  frontend:
    container_name: frontend
    image: index.docker.io/aleksioprime/streamreport_frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/home/app/backend/staticfiles
      - ./media:/home/app/backend/mediafiles
      - ./certs:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
      
volumes:
  postgres_data: