# Generated by Django 4.2.4 on 2023-12-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipation',
            name='date_end',
            field=models.DateField(null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='date_start',
            field=models.DateField(null=True, verbose_name='Дата начала'),
        ),
    ]
