# Generated by Django 3.2.18 on 2023-04-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_user_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.AddField(
            model_name='profileteacher',
            name='admin',
            field=models.BooleanField(default=False, null=True, verbose_name='Администрация'),
        ),
        migrations.AddField(
            model_name='profileteacher',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность'),
        ),
    ]
