# Generated by Django 3.2.18 on 2023-04-11 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20230409_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilestudent',
            options={'ordering': ['user'], 'verbose_name': 'Профиль студента', 'verbose_name_plural': 'Профили студентов'},
        ),
        migrations.RemoveField(
            model_name='profilestudent',
            name='group',
        ),
    ]
