# Generated by Django 3.2.18 on 2023-04-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0013_alter_periodassessment_summ_grade'),
        ('member', '0005_auto_20230411_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilestudent',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='student', to='assess.ClassGroup', verbose_name='Классы'),
        ),
    ]
