# Generated by Django 3.2.18 on 2023-04-11 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_profilestudent_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilestudent',
            name='groups',
        ),
    ]
