# Generated by Django 3.2.18 on 2023-04-18 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_remove_profilestudent_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
