# Generated by Django 3.2.18 on 2023-05-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_remove_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoleUser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_str',
        ),
    ]
