# Generated by Django 3.2.18 on 2023-05-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_auto_20230507_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name', 'active'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='profilestudent',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='profileteacher',
            name='short_name',
        ),
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Действующий пользователь'),
        ),
    ]
