# Generated by Django 3.2.18 on 2023-05-07 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_auto_20230507_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name', 'is_active'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
    ]
