# Generated by Django 3.2.18 on 2023-05-07 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0016_remove_classgroup_students'),
        ('member', '0013_auto_20230507_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilestudent',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='assess.classgroup', verbose_name='Класс'),
        ),
    ]
