# Generated by Django 3.2.18 on 2023-05-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_remove_profilestudent_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='department_photos', verbose_name='Фотография'),
        ),
    ]
