# Generated by Django 3.2.18 on 2023-05-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0016_department_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='department_pictures', verbose_name='Фотография'),
        ),
    ]
