# Generated by Django 3.2.18 on 2023-05-10 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0017_alter_department_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkLoad',
        ),
    ]
