# Generated by Django 3.2.18 on 2023-05-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0018_delete_workload'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token_dnevnik',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Токен для подключения к Дневник.РУ'),
        ),
    ]
