# Generated by Django 4.2.4 on 2023-11-21 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtlCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('name_rus', models.CharField(blank=True, max_length=64, null=True, verbose_name='Название на рус. языке')),
            ],
            options={
                'verbose_name': 'IB: ATL категория',
                'verbose_name_plural': 'IB: ATL категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('name_rus', models.CharField(max_length=64, null=True, verbose_name='Название на рус. языке')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('description_rus', models.TextField(null=True, verbose_name='Описание на рус. языке')),
            ],
            options={
                'verbose_name': 'IB: Профиль студента',
                'verbose_name_plural': 'IB: Профили студента',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AtlCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('name_rus', models.CharField(blank=True, max_length=64, null=True, verbose_name='Название на рус. языке')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='ibo.atlcategory', verbose_name='Категория ATL')),
            ],
            options={
                'verbose_name': 'IB: ATL кластер',
                'verbose_name_plural': 'IB: ATL кластеры',
                'ordering': ['category', 'id'],
            },
        ),
    ]
