# Generated by Django 4.2.4 on 2023-12-13 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtlCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('name_rus', models.CharField(blank=True, max_length=64, null=True, verbose_name='Название на рус. языке')),
            ],
            options={
                'verbose_name': 'IB: ATL категория',
                'verbose_name_plural': 'IB: ATL категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('name_rus', models.CharField(max_length=64, null=True, verbose_name='Название на рус. языке')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('description_rus', models.TextField(null=True, verbose_name='Описание на рус. языке')),
            ],
            options={
                'verbose_name': 'IB: Профиль студента',
                'verbose_name_plural': 'IB: Профили студента',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitPlanerBaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название юнита')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Номер')),
                ('hours', models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во часов')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменён')),
            ],
            options={
                'verbose_name': 'UnitPlan',
                'verbose_name_plural': 'UnitPlans',
                'ordering': ['year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UnitTeacherRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=32, null=True, verbose_name='Роль')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_roles', to='ibo.unitplanerbasemodel', verbose_name='Юнит')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_roles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'UnitPlan: Роль автора юнита',
                'verbose_name_plural': 'UnitPlan: Роли автора юнита',
                'ordering': ['unit', 'user', 'role'],
            },
        ),
        migrations.CreateModel(
            name='UnitReflectionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(blank=True, null=True, verbose_name='Пост')),
                ('type', models.CharField(choices=[('teacher', 'Рефлексия учителя'), ('students', 'Рефлексия студентов'), ('assessment', 'Рефлексия оценивания'), ('prior', 'Перед началом юнита'), ('during', 'Во время юнита'), ('after', 'После окончания юнита')], max_length=12, verbose_name='Type')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_reflections', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_posts', to='ibo.unitplanerbasemodel', verbose_name='Юнит DP')),
            ],
            options={
                'verbose_name': 'UnitPlan: Пост рефлексии',
                'verbose_name_plural': 'UnitPlans: Посты рефлексии',
                'ordering': ['unit', 'type', 'post'],
            },
        ),
        migrations.AddField(
            model_name='unitplanerbasemodel',
            name='authors',
            field=models.ManyToManyField(related_name='author_unitplans', through='ibo.UnitTeacherRoles', to=settings.AUTH_USER_MODEL, verbose_name='Авторы'),
        ),
        migrations.AddField(
            model_name='unitplanerbasemodel',
            name='teachers',
            field=models.ManyToManyField(related_name='teacher_unitplans', to=settings.AUTH_USER_MODEL, verbose_name='Учителя'),
        ),
        migrations.AddField(
            model_name='unitplanerbasemodel',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unitplans', to='general.studyyear', verbose_name='Год обучения'),
        ),
        migrations.CreateModel(
            name='IbProfileDevelop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='ibo.learnerprofile', verbose_name='Профиль студента')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ibprofiles', to='ibo.unitplanerbasemodel', verbose_name='Юнит PYP')),
            ],
            options={
                'verbose_name': 'UnitPlan: Развитие профиля студента',
                'verbose_name_plural': 'UnitPlans: Развитие профиля студента',
                'ordering': ['unit', 'profile'],
            },
        ),
        migrations.CreateModel(
            name='AtlCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('name_rus', models.CharField(blank=True, max_length=64, null=True, verbose_name='Название на рус. языке')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='ibo.atlcategory', verbose_name='Категория ATL')),
            ],
            options={
                'verbose_name': 'IB: ATL кластер',
                'verbose_name_plural': 'IB: ATL кластеры',
                'ordering': ['category', 'id'],
            },
        ),
    ]
