# Generated by Django 4.2.4 on 2023-12-11 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ibo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitplanerbasemodel',
            name='authors',
            field=models.ManyToManyField(related_name='author_unitplans', through='ibo.UnitTeacherRoles', to=settings.AUTH_USER_MODEL, verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='unitteacherroles',
            name='role',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Роль'),
        ),
    ]
