# Generated by Django 4.2.4 on 2023-11-05 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classgroup',
            name='psychologist',
        ),
        migrations.AlterField(
            model_name='user',
            name='dnevnik_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Токен доступа в Дневник'),
        ),
        migrations.CreateModel(
            name='ClassGroupRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('роль', models.CharField(max_length=255, null=True, verbose_name='Роль')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_roles', to='general.classgroup', verbose_name='Группа')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_roles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Учебный класс: роль',
                'verbose_name_plural': 'Учебные классы: роли',
                'ordering': ['user', 'group', 'роль'],
            },
        ),
        migrations.AddField(
            model_name='classgroup',
            name='extra',
            field=models.ManyToManyField(related_name='extra_classes', through='general.ClassGroupRole', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники класса'),
        ),
    ]
