# Generated by Django 4.2.4 on 2023-11-30 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_curriculum_ib'),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='curriculum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='curriculum.curriculum', verbose_name='Учебный план'),
        ),
    ]
