# Generated by Django 4.2.4 on 2023-11-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyyearib',
            name='number',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Номер параллели'),
        ),
    ]
