# Generated by Django 4.2.4 on 2023-11-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_studyyearib_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyyearib',
            options={'ordering': ['number', 'program_ib', 'name'], 'verbose_name': 'Параллель обучения IB', 'verbose_name_plural': 'Параллели обучения IB'},
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='name',
        ),
        migrations.AddField(
            model_name='academicyear',
            name='number',
            field=models.PositiveIntegerField(default=0, verbose_name='Учебный год'),
        ),
        migrations.AlterField(
            model_name='studyyearib',
            name='number',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Номер параллели IB'),
        ),
    ]
