# Generated by Django 4.2.4 on 2023-11-05 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_remove_classgroup_psychologist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
