# Generated by Django 4.2.4 on 2023-09-01 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_enterpassgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnterpassGroup',
        ),
    ]
