# Generated by Django 4.2.4 on 2023-10-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_user_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужчина'), ('female', 'Женщина'), ('None', 'Не указан')], default='none', max_length=6, null=True),
        ),
    ]
