# Generated by Django 4.2.4 on 2023-11-30 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_classgroup_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroup',
            name='year_study_ib',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='general.studyyearib', verbose_name='Год обучения по IB'),
        ),
    ]
