# Generated by Django 4.2.4 on 2023-11-08 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classgrouprole',
            options={'ordering': ['user', 'group', 'role'], 'verbose_name': 'Учебный класс: роль', 'verbose_name_plural': 'Учебные классы: роли'},
        ),
        migrations.RenameField(
            model_name='classgrouprole',
            old_name='роль',
            new_name='role',
        ),
    ]
