# Generated by Django 4.2.4 on 2023-09-01 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_alter_user_options_alter_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Учебный год')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Учебный год',
                'verbose_name_plural': 'Учебные года',
                'ordering': ['date_start'],
            },
        ),
        migrations.CreateModel(
            name='StudyYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Год обучения')),
                ('number_ib', models.CharField(max_length=12, null=True, verbose_name='Год обучения в IB')),
                ('level', models.CharField(choices=[('noo', 'Начальная школа'), ('ooo', 'Средняя школа'), ('soo', 'Старшая школа'), ('None', 'Не указано')], default='ooo', max_length=4, verbose_name='Национальные уровни образования')),
                ('program_ib', models.CharField(choices=[('pyp', 'Primary Years Programme'), ('myp', 'Middle Years Programme'), ('dp', 'Diploma Programme'), ('None', 'No program')], default=None, max_length=4, null=True, verbose_name='IB-программа')),
            ],
            options={
                'verbose_name': 'Год обучения',
                'verbose_name_plural': 'Года обучения',
                'ordering': ['number'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужчина'), ('female', 'Женщина'), ('None', 'No program')], default='none', max_length=6, null=True),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название кафедры')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='department_logos', verbose_name='Фотография')),
                ('employees', models.ManyToManyField(related_name='employees', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1, null=True, verbose_name='Литера класса')),
                ('dnevnik_id', models.CharField(max_length=255, null=True, verbose_name='ID системы Дневник.РУ')),
                ('program_ib', models.CharField(choices=[('pyp', 'Primary Years Programme'), ('myp', 'Middle Years Programme'), ('dp', 'Diploma Programme'), ('None', 'No program')], default=None, max_length=4, null=True, verbose_name='IB-программа')),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_classes', to=settings.AUTH_USER_MODEL, verbose_name='Наставник')),
                ('psychologist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psycho_classes', to=settings.AUTH_USER_MODEL, verbose_name='Психолог/воспитатель')),
                ('students', models.ManyToManyField(related_name='classes', to=settings.AUTH_USER_MODEL, verbose_name='Студенты')),
                ('year_academic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='general.academicyear', verbose_name='Учебный год')),
                ('year_study', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='general.studyyear', verbose_name='Год обучения')),
            ],
            options={
                'verbose_name': 'Учебный класс',
                'verbose_name_plural': 'Учебные классы',
                'ordering': ['year_academic', 'year_study', 'letter'],
            },
        ),
    ]
