# Generated by Django 4.2.4 on 2023-11-08 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_alter_classgrouprole_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyYearIb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, null=True, verbose_name='Название параллели IB')),
                ('program_ib', models.CharField(choices=[('pyp', 'Primary Years Programme'), ('myp', 'Middle Years Programme'), ('dp', 'Diploma Programme'), ('None', 'No program')], default=None, max_length=4, null=True, verbose_name='IB-программа')),
            ],
            options={
                'verbose_name': 'Параллель обучения IB',
                'verbose_name_plural': 'Параллели обучения IB',
                'ordering': ['program_ib', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='classgroup',
            name='program_ib',
        ),
        migrations.RemoveField(
            model_name='studyyear',
            name='number_ib',
        ),
        migrations.RemoveField(
            model_name='studyyear',
            name='program_ib',
        ),
        migrations.AddField(
            model_name='studyyear',
            name='ib',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='years', to='general.academicyear', verbose_name='Параллель по IB'),
        ),
        migrations.AlterField(
            model_name='studyyear',
            name='level',
            field=models.CharField(choices=[('noo', 'Начальная школа'), ('ooo', 'Средняя школа'), ('soo', 'Старшая школа'), ('None', 'Не указано')], default=None, max_length=4, verbose_name='Уровень образования'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='year_study_ib',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='general.studyyearib', verbose_name='Год обучения по IB'),
        ),
    ]
