# Generated by Django 4.2.4 on 2023-09-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_academicyear_studyyear_alter_user_gender_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyyear',
            name='level',
            field=models.CharField(choices=[('noo', 'Начальная школа'), ('ooo', 'Средняя школа'), ('soo', 'Старшая школа'), ('None', 'Не указано')], default=None, max_length=4, verbose_name='Национальные уровни образования'),
        ),
    ]
