# Generated by Django 4.2.4 on 2023-09-01 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_alter_studyyear_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyyear',
            options={'ordering': ['number'], 'verbose_name': 'Год обучения / параллель', 'verbose_name_plural': 'Года обучения / параллели'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name', 'is_active'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='department',
            name='employees',
            field=models.ManyToManyField(related_name='departments', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники'),
        ),
    ]
