# Generated by Django 4.2.4 on 2023-11-08 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_alter_studyyear_ib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyyear',
            name='ib',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='year', to='general.studyyearib', verbose_name='Параллель по IB'),
        ),
    ]
