# Generated by Django 4.2.4 on 2023-11-10 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_alter_studyyear_ib'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classgroup',
            options={'ordering': ['-year_academic', 'year_study', 'letter'], 'verbose_name': 'Учебный класс', 'verbose_name_plural': 'Учебные классы'},
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='dnevnik_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID системы Дневник.РУ'),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_classes', to=settings.AUTH_USER_MODEL, verbose_name='Наставник'),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='year_study',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='general.studyyear', verbose_name='Параллель'),
        ),
        migrations.AlterField(
            model_name='department',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='departments', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='studyyear',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Номер параллели'),
        ),
    ]
