# Generated by Django 4.2.4 on 2023-11-10 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_alter_classgroup_options_user_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='employees',
            field=models.ManyToManyField(blank=True, null=True, related_name='departments', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники'),
        ),
    ]
