# Generated by Django 4.2.4 on 2023-11-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_alter_department_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('М', 'Мужчина'), ('Ж', 'Женщина'), ('None', 'Не указан')], default='none', max_length=6, null=True, verbose_name='Пол'),
        ),
    ]
