# Generated by Django 4.2.4 on 2023-11-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dnevnik_user_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='ID пользователя Дневника'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dnevnik_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='ID Дневника'),
        ),
    ]
