# Generated by Django 3.2.13 on 2023-02-02 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во часов')),
            ],
            options={
                'verbose_name': 'Учебный план',
                'verbose_name_plural': 'Учебные планы',
                'ordering': ['subject', 'class_year'],
            },
        ),
        migrations.CreateModel(
            name='AchievementLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.TextField(null=True, verbose_name='Описание на англ. языке')),
                ('name_rus', models.TextField(blank=True, null=True, verbose_name='Описание на рус. языке')),
                ('point', models.PositiveIntegerField(default=0, verbose_name='Баллы')),
            ],
            options={
                'verbose_name': 'Уровень достижений',
                'verbose_name_plural': 'Уровни достижений',
                'ordering': ['objective', 'point'],
            },
        ),
        migrations.CreateModel(
            name='Aim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, null=True, verbose_name='Название на англ. языке')),
                ('name_rus', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на рус. языке')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
                'ordering': ['subject_group', 'name_eng'],
            },
        ),
        migrations.CreateModel(
            name='ATLMappingMYP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(blank=True, null=True, verbose_name='Описание учебных действий')),
            ],
            options={
                'verbose_name': 'UnitPlan MYP: Карта навыков ATL',
                'verbose_name_plural': 'UnitPlan MYP: Карты навыков ATL',
                'ordering': ['planner', 'strand'],
            },
        ),
        migrations.CreateModel(
            name='CategoryATL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=64, verbose_name='Название на англ. языке')),
                ('name_rus', models.CharField(blank=True, max_length=64, null=True, verbose_name='Название на рус. языке')),
            ],
            options={
                'verbose_name': 'ATL: Категория ',
                'verbose_name_plural': 'ATL: Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ClassYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_rus', models.PositiveIntegerField(verbose_name='Год обучения в РФ')),
                ('year_ib', models.CharField(blank=True, max_length=12, null=True, verbose_name='Год обучения в IB')),
                ('program', models.CharField(choices=[('PYP', 'Primary Years Programme'), ('MYP', 'Middle Years Programme'), ('DP', 'Diploma Programme'), ('FGOS', 'ФГОС')], default='FGOS', max_length=4)),
            ],
            options={
                'verbose_name': 'Год обучения',
                'verbose_name_plural': 'Года обучения',
            },
        ),
        migrations.CreateModel(
            name='ClusterATL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=64, verbose_name='Название на англ. языке')),
                ('name_rus', models.CharField(blank=True, max_length=64, null=True, verbose_name='Название на рус. языке')),
            ],
            options={
                'verbose_name': 'ATL: Кластер',
                'verbose_name_plural': 'ATL: Кластеры',
                'ordering': ['category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(choices=[('A', 'Критерий A'), ('B', 'Критерий B'), ('C', 'Критерий C'), ('D', 'Критерий D')], max_length=1)),
                ('name_eng', models.CharField(max_length=255, verbose_name='Название на англ. языке')),
                ('name_rus', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на рус. языке')),
                ('description_eng', models.TextField(blank=True, null=True, verbose_name='Описание на англ. языке')),
                ('description_rus', models.TextField(blank=True, null=True, verbose_name='Описание на рус. языке')),
            ],
            options={
                'verbose_name': 'Критерий оценивания',
                'verbose_name_plural': 'Критерии оценивания',
                'ordering': ['subject_group', 'letter'],
            },
        ),
        migrations.CreateModel(
            name='ExplorationToDevelop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=64, verbose_name='Название на англ. языке')),
                ('name_rus', models.CharField(blank=True, max_length=64, null=True, verbose_name='Название на рус. языке')),
            ],
            options={
                'verbose_name': 'GC: Линия исследования',
                'verbose_name_plural': 'GC: Линии исследований',
                'ordering': ['gcontext', 'name_eng'],
            },
        ),
        migrations.CreateModel(
            name='GlobalContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=64, verbose_name='Название на англ. языке')),
                ('name_rus', models.CharField(blank=True, max_length=64, null=True, verbose_name='Название на рус. языке')),
                ('description_eng', models.TextField(blank=True, null=True, verbose_name='Описание на англ. языке')),
                ('description_rus', models.TextField(blank=True, null=True, verbose_name='Описание на рус. языке')),
                ('focus_questions_eng', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вопросы на англ. языке')),
                ('focus_questions_rus', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вопросы на рус. языке')),
            ],
            options={
                'verbose_name': 'GC: Глобальный контекст',
                'verbose_name_plural': 'GC: Глобальные контексты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InquiryQuestionDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('type_inq', models.CharField(choices=[('Skills-based', 'Skills-based'), ('Content-based', 'Content-based'), ('Debatable', 'Debatable'), ('Concept-based', 'Concept-based')], default='Skills-based', max_length=24, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'UnitPlan DP: Исследовательский вопрос',
                'verbose_name_plural': 'UnitPlan DP: Исследовательские вопросы',
                'ordering': ['type_inq', 'question'],
            },
        ),
        migrations.CreateModel(
            name='InquiryQuestionMYP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Исследовательский вопрос')),
                ('type_inq', models.CharField(choices=[('Factual', 'Фактический'), ('Conceptual', 'Концептуальный'), ('Debatable', 'Дискуссионный')], default='Factual', max_length=12, verbose_name='Тип вопроса')),
                ('line', models.CharField(blank=True, max_length=255, null=True, verbose_name='Линия исследования')),
            ],
            options={
                'verbose_name': 'UnitPlan MYP: Исследовательский вопрос',
                'verbose_name_plural': 'UnitPlan MYP: Исследовательские вопросы',
                'ordering': ['type_inq', 'question'],
            },
        ),
        migrations.CreateModel(
            name='KeyConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=32, verbose_name='Название на англ. языке')),
                ('name_rus', models.CharField(blank=True, max_length=32, null=True, verbose_name='Название на рус. языке')),
                ('description_eng', models.TextField(blank=True, null=True, verbose_name='Описание на англ. языке')),
                ('description_rus', models.TextField(blank=True, null=True, verbose_name='Описание на рус. языке')),
            ],
            options={
                'verbose_name': 'KC: Ключевой концепт',
                'verbose_name_plural': 'KC: Ключевые концепты',
                'ordering': ['name_eng'],
            },
        ),
        migrations.CreateModel(
            name='LearnerProfileIB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, null=True, verbose_name='Название на англ. языке')),
                ('name_rus', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на рус. языке')),
                ('description_eng', models.TextField(blank=True, null=True, verbose_name='Описание на англ. языке')),
                ('description_rus', models.TextField(blank=True, null=True, verbose_name='Описание на рус. языке')),
            ],
            options={
                'verbose_name': 'Профиль студента',
                'verbose_name_plural': 'Профили студента',
                'ordering': ['name_eng'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, null=True, verbose_name='Название на англ. языке')),
                ('name_rus', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на рус. языке')),
            ],
            options={
                'verbose_name': 'Образовательный уровень',
                'verbose_name_plural': 'Образовательные уровни',
                'ordering': ['name_eng'],
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, null=True, verbose_name='Описание на англ. языке')),
                ('name_rus', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание на рус. языке')),
            ],
            options={
                'verbose_name': 'Образовательная цель',
                'verbose_name_plural': 'Образовательные цели',
                'ordering': ['level', 'strand'],
            },
        ),
        migrations.CreateModel(
            name='RecommendSubjectKC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_eng', models.TextField(blank=True, null=True, verbose_name='Комментарии на англ. языке')),
                ('comment_rus', models.TextField(blank=True, null=True, verbose_name='Комментарии на рус. языке')),
            ],
            options={
                'verbose_name': 'KC: Рекомендуемый предмет',
                'verbose_name_plural': 'KC: Рекомендуемые предметы',
                'ordering': ['subject_group', 'key_concept'],
            },
        ),
        migrations.CreateModel(
            name='ReflectionDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_post', models.CharField(choices=[('Prior', 'Prior to studying the unit'), ('During', 'During the unit'), ('Worked Well', 'What worked well'), ('Didn’t work well', 'What didn’t work well'), ('Transfer reflection', 'Transfer reflection')], default='Prior', max_length=24, verbose_name='Type')),
                ('post', models.TextField(blank=True, null=True, verbose_name='Post')),
            ],
            options={
                'verbose_name': 'UnitPlan DP: Пост рефлексии',
                'verbose_name_plural': 'UnitPlan DP: Посты рефлексии',
                'ordering': ['planner', 'type_post'],
            },
        ),
        migrations.CreateModel(
            name='ReflectionMYP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_post', models.CharField(choices=[('Prior', 'Перед началом юнита'), ('During', 'Во время юнита'), ('After', 'После окончания юнита')], default='After', max_length=6, verbose_name='Тип рефлексии')),
                ('post', models.TextField(blank=True, null=True, verbose_name='Содержание рефлексии')),
            ],
            options={
                'verbose_name': 'UnitPlan MYP: Пост рефлексии',
                'verbose_name_plural': 'UnitPlan MYP: Посты рефлексии',
                'ordering': ['planner', 'type_post'],
            },
        ),
        migrations.CreateModel(
            name='RelatedConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=64, verbose_name='Название на англ. языке')),
                ('name_rus', models.CharField(blank=True, max_length=64, null=True, verbose_name='Название на рус. языке')),
                ('description_eng', models.TextField(blank=True, null=True, verbose_name='Описание на англ. языке')),
                ('description_rus', models.TextField(blank=True, null=True, verbose_name='Описание на рус. языке')),
            ],
            options={
                'verbose_name': 'RC: Предметный концепт',
                'verbose_name_plural': 'RC: Предметные концепты',
                'ordering': ['id', 'name_eng'],
            },
        ),
        migrations.CreateModel(
            name='SkillATL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, verbose_name='Название на англ. языке')),
                ('name_rus', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на рус. языке')),
                ('description_eng', models.TextField(blank=True, null=True, verbose_name='Описание на англ. языке')),
                ('description_rus', models.TextField(blank=True, null=True, verbose_name='Описание на рус. языке')),
            ],
            options={
                'verbose_name': 'ATL: Навыки',
                'verbose_name_plural': 'ATL: Навыки',
                'ordering': ['cluster', 'name_eng'],
            },
        ),
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='Абсолютный номер')),
                ('letter', models.PositiveIntegerField(choices=[(1, 'i'), (2, 'ii'), (3, 'iii'), (4, 'iv'), (5, 'v')], default=1, verbose_name='Метка в критерии')),
                ('name_eng', models.CharField(max_length=255, verbose_name='Название на англ. языке')),
                ('name_rus', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на рус. языке')),
            ],
            options={
                'verbose_name': 'Стрэнд',
                'verbose_name_plural': 'Стрэнды',
                'ordering': ['criterion', 'number', 'letter'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rus', models.CharField(max_length=128, verbose_name='Название на рус. языке')),
                ('name_eng', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название на англ. языке')),
                ('type_subject', models.CharField(choices=[('base', 'Обязательная часть'), ('extra', 'Внеурочная деятельность')], default='base', max_length=5, verbose_name='Тип предмета')),
                ('id_dnevnik', models.CharField(blank=True, max_length=40, null=True, verbose_name='ID системы Дневник.РУ')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['group_ib', 'name_eng'],
            },
        ),
        migrations.CreateModel(
            name='SubjectDirectionRC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=128, verbose_name='Название на англ. языке')),
                ('name_rus', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название на рус. языке')),
            ],
            options={
                'verbose_name': 'RC: Предметное направление',
                'verbose_name_plural': 'RC: Предметные направления',
                'ordering': ['id', 'name_eng'],
            },
        ),
        migrations.CreateModel(
            name='SubjectGroupFGOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rus', models.CharField(max_length=128, verbose_name='Название на рус. языке')),
                ('type_group', models.CharField(choices=[('area', 'Предметная область'), ('direction', 'Направление')], default='area', max_length=9, verbose_name='Тип группы')),
                ('level', models.CharField(choices=[('noo', 'Начальная школа'), ('ooo', 'Средняя школа'), ('soo', 'Старшая школа'), ('dpsoo', 'DP в старшей школе')], default='ooo', max_length=5, verbose_name='Уровень образования')),
            ],
            options={
                'verbose_name': 'Предметная группа ФГОС',
                'verbose_name_plural': 'Предметные группы ФГОС',
                'ordering': ['level', 'type_group', 'name_rus'],
            },
        ),
        migrations.CreateModel(
            name='SubjectGroupIB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=128, verbose_name='Название на англ. языке')),
                ('name_rus', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название на рус. языке')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='subjectgroup_pic', verbose_name='Картинка')),
                ('program', models.CharField(choices=[('PYP', 'Primary Years Programme'), ('MYP', 'Middle Years Programme'), ('DP', 'Diploma Programme'), ('FGOS', 'ФГОС')], default='FGOS', max_length=4)),
            ],
            options={
                'verbose_name': 'Предметная группа IB',
                'verbose_name_plural': 'Предметные группы IB',
                'ordering': ['program', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubjectLevelMYP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'UnitPlan MYP: Выбор предмета и уровня',
                'verbose_name_plural': 'UnitPlan MYP: Выборы предметов и уровней',
                'ordering': ['unit', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='UnitPlannerDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('levels', models.CharField(choices=[('SL', 'Standart Level'), ('HL', 'High Level'), ('SL+HL', 'Standart + High Level')], default='SL+HL', max_length=5, verbose_name='Levels')),
                ('hours', models.PositiveSmallIntegerField(default=0, verbose_name='Hours')),
                ('course_part', models.CharField(max_length=255, verbose_name='Course Part')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('transfer_goals', models.TextField(blank=True, null=True, verbose_name='Transfer goals')),
                ('essen_understand', models.TextField(blank=True, null=True, verbose_name='Essential Understandings')),
                ('misunderstand', models.TextField(blank=True, null=True, verbose_name='Missed concepts/misunderstandings')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='Skills')),
                ('concepts', models.TextField(blank=True, null=True, verbose_name='Concepts')),
                ('international_mindedness', models.TextField(blank=True, null=True, verbose_name='International Mindedness')),
                ('academic_integrity', models.TextField(blank=True, null=True, verbose_name='Academic Integrity')),
                ('infocom_technology', models.TextField(blank=True, null=True, verbose_name='Information Communication Technology')),
                ('description_atl', models.TextField(blank=True, null=True, verbose_name='Description ATL')),
                ('description_lp', models.TextField(blank=True, null=True, verbose_name='Description Learning Profile')),
                ('formative_assessment', models.TextField(blank=True, null=True, verbose_name='Formative assessment')),
                ('summative_assessment', models.TextField(blank=True, null=True, verbose_name='Summative assessment')),
                ('peer_self_assessment', models.TextField(blank=True, null=True, verbose_name='Peer and self assessment')),
                ('standardization_moderation', models.TextField(blank=True, null=True, verbose_name='Standardization and moderation')),
                ('description_criteria', models.TextField(blank=True, null=True, verbose_name='Description Criteria')),
                ('prior_experiences', models.TextField(blank=True, null=True, verbose_name='Prior learning experience')),
                ('pedagogical_approaches', models.TextField(blank=True, null=True, verbose_name='Pedagogical approaches')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Feedback')),
                ('student_expectations', models.TextField(blank=True, null=True, verbose_name='Student expectations')),
            ],
            options={
                'verbose_name': 'UnitPlan DP: Основные данные юнита',
                'verbose_name_plural': 'UnitPlan DP: Основные данные юнитов',
                'ordering': ['class_year', 'subject', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UnitPlannerMYP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название юнита')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Номер')),
                ('hours', models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во часов')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('conceptual_understanding', models.TextField(blank=True, null=True, verbose_name='Концептуальное понимание')),
                ('statement_inquiry', models.TextField(blank=True, null=True, verbose_name='Формулировка исследования')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержание (темы, знания и умения)')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='Умения')),
                ('description_lp', models.TextField(blank=True, null=True, verbose_name='Описание развития профиля')),
                ('international_mindedness', models.TextField(blank=True, null=True, verbose_name='Межкультурное понимание')),
                ('academic_integrity', models.TextField(blank=True, null=True, verbose_name='Академическая честность')),
                ('language_development', models.TextField(blank=True, null=True, verbose_name='Языковое развитие')),
                ('infocom_technology', models.TextField(blank=True, null=True, verbose_name='Использование средств ИКТ')),
                ('service_as_action', models.TextField(blank=True, null=True, verbose_name='Служение как действие')),
                ('formative_assessment', models.TextField(blank=True, null=True, verbose_name='Формирующее оценивание')),
                ('summative_assessment_task', models.TextField(blank=True, null=True, verbose_name='Итоговое оценивание (задачи)')),
                ('summative_assessment_soi', models.TextField(blank=True, null=True, verbose_name='Итоговое оценивание (взаимосвязь с SOI)')),
                ('peer_self_assessment', models.TextField(blank=True, null=True, verbose_name='Взаимное и самооценивание')),
                ('standardization_moderation', models.TextField(blank=True, null=True, verbose_name='Стандартизация и модерация')),
                ('prior_experiences', models.TextField(blank=True, null=True, verbose_name='Предыдущий опыт обучения')),
                ('learning_experiences', models.TextField(blank=True, null=True, verbose_name='Учебная деятельность')),
                ('teaching_strategies', models.TextField(blank=True, null=True, verbose_name='Стратегии преподавания')),
                ('student_expectations', models.TextField(blank=True, null=True, verbose_name='Ожидания студентов')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Обратная связь')),
                ('differentiation', models.TextField(blank=True, null=True, verbose_name='Дифференцированный подход')),
                ('aims', models.ManyToManyField(blank=True, related_name='unitplan_myp', to='curriculum.Aim', verbose_name='Цели')),
            ],
            options={
                'verbose_name': 'UnitPlan MYP: Основные данные юнита',
                'verbose_name_plural': 'UnitPlan MYP: Основные данные юнитов',
                'ordering': ['class_year', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UnitPlannerMYPID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_integration', models.TextField(blank=True, null=True, verbose_name='Формы интеграции')),
                ('purpose_integration', models.TextField(blank=True, null=True, verbose_name='Цель интеграции')),
                ('interdisciplinary_links', models.TextField(blank=True, null=True, verbose_name='Междисциплинарные связи')),
                ('inter_aims', models.ManyToManyField(blank=True, related_name='inter', to='curriculum.Aim', verbose_name='Цели')),
                ('inter_criteria', models.ManyToManyField(blank=True, related_name='inter', to='curriculum.Criterion', verbose_name='Критерии оценки')),
                ('inter_strands', models.ManyToManyField(blank=True, related_name='inter', to='curriculum.Strand', verbose_name='Образовательные цели')),
                ('unitplan_myp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inter', to='curriculum.unitplannermyp', verbose_name='ЮнитПланер MYP')),
            ],
            options={
                'verbose_name': 'UnitPlan MYP: Междисциплинарность',
                'verbose_name_plural': 'UnitPlan MYP: Междисциплинарности',
                'ordering': ['unitplan_myp'],
            },
        ),
    ]
