# Generated by Django 3.2.13 on 2023-02-02 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assess', '0001_initial'),
        ('curriculum', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitplannermyp',
            name='authors',
            field=models.ManyToManyField(related_name='unitplan_myp', to='member.ProfileTeacher', verbose_name='Авторы'),
        ),
        migrations.AddField(
            model_name='unitplannermyp',
            name='class_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unitplan_myp', to='curriculum.classyear', verbose_name='Год обучения'),
        ),
        migrations.AddField(
            model_name='unitplannermyp',
            name='criteria',
            field=models.ManyToManyField(blank=True, related_name='unitplan_myp', to='curriculum.Criterion', verbose_name='Критерии оценки'),
        ),
        migrations.AddField(
            model_name='unitplannermyp',
            name='explorations',
            field=models.ManyToManyField(blank=True, related_name='unitplan_myp', to='curriculum.ExplorationToDevelop', verbose_name='Линии исследования'),
        ),
        migrations.AddField(
            model_name='unitplannermyp',
            name='global_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unitplan_myp', to='curriculum.globalcontext', verbose_name='Глобальный контекст'),
        ),
        migrations.AddField(
            model_name='unitplannermyp',
            name='key_concepts',
            field=models.ManyToManyField(blank=True, related_name='unitplan_myp', to='curriculum.KeyConcept', verbose_name='Ключевые концепты'),
        ),
        migrations.AddField(
            model_name='unitplannermyp',
            name='learner_profile',
            field=models.ManyToManyField(blank=True, related_name='unitplan_myp', to='curriculum.LearnerProfileIB', verbose_name='Профиль студента'),
        ),
        migrations.AddField(
            model_name='unitplannermyp',
            name='related_concepts',
            field=models.ManyToManyField(blank=True, related_name='unitplan_myp', to='curriculum.RelatedConcept', verbose_name='Сопутствующие концепты'),
        ),
        migrations.AddField(
            model_name='unitplannermyp',
            name='strands',
            field=models.ManyToManyField(blank=True, related_name='unitplan_myp', to='curriculum.Strand', verbose_name='Стренды предметной группы'),
        ),
        migrations.AddField(
            model_name='unitplannermyp',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='unitplan_myp', through='curriculum.SubjectLevelMYP', to='curriculum.Subject', verbose_name='Предметы'),
        ),
        migrations.AddField(
            model_name='unitplannerdp',
            name='class_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unitplan_dp', to='curriculum.classyear', verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='unitplannerdp',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unitplan_dp', to='curriculum.subject', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='subjectlevelmyp',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_unit', to='curriculum.level', verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='subjectlevelmyp',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_unit', to='curriculum.subject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='subjectlevelmyp',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_unit', to='curriculum.unitplannermyp', verbose_name='Юнит'),
        ),
        migrations.AddField(
            model_name='subjectdirectionrc',
            name='subject_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connect_subjectrc', to='curriculum.subjectgroupib', verbose_name='Предметная группа'),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject', to='member.department', verbose_name='Учебное подразделение'),
        ),
        migrations.AddField(
            model_name='subject',
            name='group_fgos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject', to='curriculum.subjectgroupfgos', verbose_name='Предметная область в РФ'),
        ),
        migrations.AddField(
            model_name='subject',
            name='group_ib',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject', to='curriculum.subjectgroupib', verbose_name='Предметная группа в IB'),
        ),
        migrations.AddField(
            model_name='strand',
            name='criterion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strand', to='curriculum.criterion', verbose_name='Критерий'),
        ),
        migrations.AddField(
            model_name='skillatl',
            name='cluster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skillATL', to='curriculum.clusteratl', verbose_name='Кластер ATL'),
        ),
        migrations.AddField(
            model_name='relatedconcept',
            name='subject_directions',
            field=models.ManyToManyField(related_name='related_concept', to='curriculum.SubjectDirectionRC', verbose_name='Предметное направление'),
        ),
        migrations.AddField(
            model_name='reflectionmyp',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reflections', to='member.profileteacher', verbose_name='Автор поста'),
        ),
        migrations.AddField(
            model_name='reflectionmyp',
            name='planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='curriculum.unitplannermyp', verbose_name='Планнер MYP'),
        ),
        migrations.AddField(
            model_name='reflectiondp',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reflection_dp', to='member.profileteacher', verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='reflectiondp',
            name='planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='curriculum.unitplannerdp', verbose_name='Planner DP'),
        ),
        migrations.AddField(
            model_name='recommendsubjectkc',
            name='key_concept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomend_subject', to='curriculum.keyconcept', verbose_name='Ключевой концепт'),
        ),
        migrations.AddField(
            model_name='recommendsubjectkc',
            name='subject_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomend_subject', to='curriculum.subjectgroupib', verbose_name='Предметная группа'),
        ),
        migrations.AddField(
            model_name='objective',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objective', to='curriculum.level', verbose_name='Уровень в IB'),
        ),
        migrations.AddField(
            model_name='objective',
            name='strand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objective', to='curriculum.strand', verbose_name='Стрэнд'),
        ),
        migrations.AddField(
            model_name='level',
            name='subject_groups',
            field=models.ManyToManyField(blank=True, related_name='level', to='curriculum.SubjectGroupIB', verbose_name='Предметные группы'),
        ),
        migrations.AddField(
            model_name='keyconcept',
            name='recommended_subjects',
            field=models.ManyToManyField(blank=True, related_name='key_concept', through='curriculum.RecommendSubjectKC', to='curriculum.SubjectGroupIB', verbose_name='Рекомендуемые предметные группы'),
        ),
        migrations.AddField(
            model_name='inquiryquestionmyp',
            name='planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquestions', to='curriculum.unitplannermyp', verbose_name='Планнер MYP'),
        ),
        migrations.AddField(
            model_name='inquiryquestiondp',
            name='planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquestions', to='curriculum.unitplannerdp', verbose_name='Planner DP'),
        ),
        migrations.AddField(
            model_name='explorationtodevelop',
            name='gcontext',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exploration', to='curriculum.globalcontext', verbose_name='Глобальный контекст'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='subject_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criterion', to='curriculum.subjectgroupib', verbose_name='Предметная группа'),
        ),
        migrations.AddField(
            model_name='clusteratl',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cluster', to='curriculum.categoryatl', verbose_name='Категория ATL'),
        ),
        migrations.AddField(
            model_name='atlmappingmyp',
            name='atl',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='atlmapping', to='curriculum.skillatl', verbose_name='Навыки ATL'),
        ),
        migrations.AddField(
            model_name='atlmappingmyp',
            name='planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atlmapping', to='curriculum.unitplannermyp', verbose_name='Планнер MYP'),
        ),
        migrations.AddField(
            model_name='atlmappingmyp',
            name='strand',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='atlmapping', to='curriculum.strand', verbose_name='Предметный стрэнд'),
        ),
        migrations.AddField(
            model_name='aim',
            name='subject_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aim', to='curriculum.subjectgroupib', verbose_name='Предметная группа'),
        ),
        migrations.AddField(
            model_name='achievementlevel',
            name='objective',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievelevel', to='curriculum.objective', verbose_name='Образовательная цель'),
        ),
        migrations.AddField(
            model_name='academicplan',
            name='class_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='curriculum.classyear', verbose_name='Год обучения'),
        ),
        migrations.AddField(
            model_name='academicplan',
            name='study_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='assess.studyyear', verbose_name='Учебный год'),
        ),
        migrations.AddField(
            model_name='academicplan',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='curriculum.subject', verbose_name='Предмет'),
        ),
    ]
