# Generated by Django 3.2.13 on 2023-02-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitplannermyp',
            name='resources',
            field=models.TextField(blank=True, null=True, verbose_name='Ресурсы'),
        ),
    ]
