# Generated by Django 3.2.18 on 2023-04-30 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_unitplannermyp_resources'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atlmappingmyp',
            options={'ordering': ['strand'], 'verbose_name': 'UnitPlan MYP: Карта навыков ATL', 'verbose_name_plural': 'UnitPlan MYP: Карты навыков ATL'},
        ),
        migrations.AlterModelOptions(
            name='inquiryquestionmyp',
            options={'ordering': ['type', 'question'], 'verbose_name': 'UnitPlan MYP: Исследовательский вопрос', 'verbose_name_plural': 'UnitPlan MYP: Исследовательские вопросы'},
        ),
        migrations.AlterModelOptions(
            name='reflectionmyp',
            options={'ordering': ['type', 'post'], 'verbose_name': 'UnitPlan MYP: Пост рефлексии', 'verbose_name_plural': 'UnitPlan MYP: Посты рефлексии'},
        ),
        migrations.AlterModelOptions(
            name='unitplannermypid',
            options={'ordering': ['title'], 'verbose_name': 'UnitPlan MYP: Междисциплинарность', 'verbose_name_plural': 'UnitPlan MYP: Междисциплинарности'},
        ),
        migrations.RenameField(
            model_name='inquiryquestionmyp',
            old_name='type_inq',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='reflectionmyp',
            old_name='type_post',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='atlmappingmyp',
            name='planner',
        ),
        migrations.RemoveField(
            model_name='inquiryquestionmyp',
            name='planner',
        ),
        migrations.RemoveField(
            model_name='reflectionmyp',
            name='planner',
        ),
        migrations.RemoveField(
            model_name='unitplannermyp',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='unitplannermypid',
            name='unitplan_myp',
        ),
        migrations.AddField(
            model_name='unitplannermyp',
            name='atl_mapping',
            field=models.ManyToManyField(blank=True, related_name='unitplan_myp', to='curriculum.ATLMappingMYP', verbose_name='Карта навыков'),
        ),
        migrations.AddField(
            model_name='unitplannermyp',
            name='inquiry_questions',
            field=models.ManyToManyField(blank=True, related_name='unitplan_myp', to='curriculum.InquiryQuestionMYP', verbose_name='Исследовательские вопросы'),
        ),
        migrations.AddField(
            model_name='unitplannermyp',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unitplan_myp', to='curriculum.level', verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='unitplannermyp',
            name='reflections',
            field=models.ManyToManyField(blank=True, related_name='unitplan_myp', to='curriculum.ReflectionMYP', verbose_name='Рефлексия'),
        ),
        migrations.AddField(
            model_name='unitplannermyp',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unitplan_myp', to='curriculum.subject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='unitplannermypid',
            name='title',
            field=models.CharField(default='Название', max_length=255, verbose_name='Название междисциплинарного юнита'),
            preserve_default='Название',
        ),
        migrations.AddField(
            model_name='unitplannermypid',
            name='units',
            field=models.ManyToManyField(related_name='inter', to='curriculum.UnitPlannerMYP', verbose_name='Юниты MYP'),
        ),
        migrations.DeleteModel(
            name='SubjectLevelMYP',
        ),
    ]
