# Generated by Django 3.2.18 on 2023-05-04 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_auto_20230430_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitplannermyp',
            name='learner_profile',
        ),
        migrations.AlterField(
            model_name='unitplannermypid',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название междисциплинарного юнита'),
        ),
        migrations.CreateModel(
            name='DevelopProfileMYP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Междисциплинарные связи')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='develop_myp', to='curriculum.learnerprofileib', verbose_name='Профиль студента')),
            ],
            options={
                'verbose_name': 'UnitPlan MYP: Развития профиля студента',
                'verbose_name_plural': 'UnitPlan MYP: Развития профилей студента',
                'ordering': ['profile'],
            },
        ),
    ]
