# Generated by Django 3.2.18 on 2023-05-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_auto_20230504_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitplannermyp',
            name='learner_profile',
            field=models.ManyToManyField(blank=True, related_name='unitplan_myp', to='curriculum.DevelopProfileMYP', verbose_name='Профиль студента'),
        ),
    ]
