# Generated by Django 3.2.18 on 2023-05-04 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_unitplannermyp_learner_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitplannermyp',
            name='description',
        ),
        migrations.RemoveField(
            model_name='unitplannermyp',
            name='description_lp',
        ),
    ]
