# Generated by Django 3.2.18 on 2023-05-05 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_auto_20230504_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitplannermypid',
            options={'ordering': ['title'], 'verbose_name': 'UnitPlan MYP: Междисциплинарный юнит', 'verbose_name_plural': 'UnitPlan MYP: Междисциплинарные юниты'},
        ),
        migrations.RenameField(
            model_name='unitplannermypid',
            old_name='inter_aims',
            new_name='aims_idu',
        ),
        migrations.RenameField(
            model_name='unitplannermypid',
            old_name='inter_criteria',
            new_name='criteria_idu',
        ),
        migrations.RenameField(
            model_name='unitplannermypid',
            old_name='inter_strands',
            new_name='strands_idu',
        ),
        migrations.RemoveField(
            model_name='unitplannermypid',
            name='form_integration',
        ),
        migrations.RemoveField(
            model_name='unitplannermypid',
            name='interdisciplinary_links',
        ),
        migrations.AddField(
            model_name='unitplannermypid',
            name='conceptual_understanding',
            field=models.TextField(blank=True, null=True, verbose_name='Концептуальное понимание'),
        ),
        migrations.AddField(
            model_name='unitplannermypid',
            name='differentiation',
            field=models.TextField(blank=True, null=True, verbose_name='Дифференцированный подход'),
        ),
        migrations.AddField(
            model_name='unitplannermypid',
            name='explorations',
            field=models.ManyToManyField(blank=True, related_name='inter', to='curriculum.ExplorationToDevelop', verbose_name='Линии исследования'),
        ),
        migrations.AddField(
            model_name='unitplannermypid',
            name='formative_assessment',
            field=models.TextField(blank=True, null=True, verbose_name='Формирующее оценивание'),
        ),
        migrations.AddField(
            model_name='unitplannermypid',
            name='global_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inter', to='curriculum.globalcontext', verbose_name='Глобальный контекст'),
        ),
        migrations.AddField(
            model_name='unitplannermypid',
            name='hours',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во часов'),
        ),
        migrations.AddField(
            model_name='unitplannermypid',
            name='inquiry_questions',
            field=models.ManyToManyField(blank=True, related_name='inter', to='curriculum.InquiryQuestionMYP', verbose_name='Исследовательские вопросы'),
        ),
        migrations.AddField(
            model_name='unitplannermypid',
            name='introduction_idu',
            field=models.TextField(blank=True, null=True, verbose_name='Введение в МДП'),
        ),
        migrations.AddField(
            model_name='unitplannermypid',
            name='key_concepts',
            field=models.ManyToManyField(blank=True, related_name='inter', to='curriculum.KeyConcept', verbose_name='Ключевые концепты'),
        ),
        migrations.AddField(
            model_name='unitplannermypid',
            name='learning_teaching',
            field=models.TextField(blank=True, null=True, verbose_name='Учебная деятельность'),
        ),
        migrations.AddField(
            model_name='unitplannermypid',
            name='reflections',
            field=models.ManyToManyField(blank=True, related_name='inter', to='curriculum.ReflectionMYP', verbose_name='Рефлексия'),
        ),
        migrations.AddField(
            model_name='unitplannermypid',
            name='related_concepts',
            field=models.ManyToManyField(blank=True, related_name='inter', to='curriculum.RelatedConcept', verbose_name='Сопутствующие концепты'),
        ),
        migrations.AddField(
            model_name='unitplannermypid',
            name='statement_inquiry',
            field=models.TextField(blank=True, null=True, verbose_name='Формулировка исследования'),
        ),
        migrations.AddField(
            model_name='unitplannermypid',
            name='summative_assessment',
            field=models.TextField(blank=True, null=True, verbose_name='Итоговое оценивание'),
        ),
        migrations.AddField(
            model_name='unitplannermypid',
            name='tasks',
            field=models.TextField(blank=True, null=True, verbose_name='Задания'),
        ),
    ]
