# Generated by Django 3.2.18 on 2023-05-05 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_auto_20230505_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitplannermypid',
            name='units',
        ),
        migrations.AddField(
            model_name='unitplannermyp',
            name='interdisciplinary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unitplan_myp', to='curriculum.unitplannermypid', verbose_name='Междисциплинарный юнит'),
        ),
    ]
