# Generated by Django 3.2.18 on 2023-05-05 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_auto_20230505_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitplannermypid',
            old_name='introduction_idu',
            new_name='introduction',
        ),
        migrations.RemoveField(
            model_name='unitplannermypid',
            name='aims_idu',
        ),
        migrations.RemoveField(
            model_name='unitplannermypid',
            name='criteria_idu',
        ),
        migrations.RemoveField(
            model_name='unitplannermypid',
            name='strands_idu',
        ),
        migrations.AddField(
            model_name='unitplannermypid',
            name='aims',
            field=models.ManyToManyField(blank=True, related_name='idu', to='curriculum.Aim', verbose_name='Цели'),
        ),
        migrations.AddField(
            model_name='unitplannermypid',
            name='class_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idu', to='curriculum.classyear', verbose_name='Год обучения'),
        ),
        migrations.AddField(
            model_name='unitplannermypid',
            name='criteria',
            field=models.ManyToManyField(blank=True, related_name='idu', to='curriculum.Criterion', verbose_name='Критерии оценки'),
        ),
        migrations.AddField(
            model_name='unitplannermypid',
            name='strands',
            field=models.ManyToManyField(blank=True, related_name='idu', to='curriculum.Strand', verbose_name='Образовательные цели'),
        ),
        migrations.AlterField(
            model_name='unitplannermypid',
            name='explorations',
            field=models.ManyToManyField(blank=True, related_name='idu', to='curriculum.ExplorationToDevelop', verbose_name='Линии исследования'),
        ),
        migrations.AlterField(
            model_name='unitplannermypid',
            name='global_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idu', to='curriculum.globalcontext', verbose_name='Глобальный контекст'),
        ),
        migrations.AlterField(
            model_name='unitplannermypid',
            name='inquiry_questions',
            field=models.ManyToManyField(blank=True, related_name='idu', to='curriculum.InquiryQuestionMYP', verbose_name='Исследовательские вопросы'),
        ),
        migrations.AlterField(
            model_name='unitplannermypid',
            name='key_concepts',
            field=models.ManyToManyField(blank=True, related_name='idu', to='curriculum.KeyConcept', verbose_name='Ключевые концепты'),
        ),
        migrations.AlterField(
            model_name='unitplannermypid',
            name='reflections',
            field=models.ManyToManyField(blank=True, related_name='idu', to='curriculum.ReflectionMYP', verbose_name='Рефлексия'),
        ),
        migrations.AlterField(
            model_name='unitplannermypid',
            name='related_concepts',
            field=models.ManyToManyField(blank=True, related_name='idu', to='curriculum.RelatedConcept', verbose_name='Сопутствующие концепты'),
        ),
    ]
