# Generated by Django 3.2.18 on 2023-05-06 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0010_auto_20230505_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitplannerdp',
            name='description',
        ),
        migrations.RemoveField(
            model_name='unitplannerdp',
            name='levels',
        ),
    ]
