# Generated by Django 3.2.18 on 2023-05-08 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0011_auto_20230507_0221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitplannermyp',
            options={'ordering': ['class_year', 'subject', 'order', 'title'], 'verbose_name': 'UnitPlan MYP: Основные данные юнита', 'verbose_name_plural': 'UnitPlan MYP: Основные данные юнитов'},
        ),
    ]
