# Generated by Django 3.2.18 on 2023-05-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0012_alter_unitplannermyp_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='number',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер'),
        ),
    ]
