# Generated by Django 3.2.18 on 2023-05-10 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0013_level_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcademicPlan',
        ),
    ]
