# Generated by Django 3.2.18 on 2023-05-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0014_delete_academicplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['group_ib', 'name_rus'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
    ]
