# Generated by Django 3.2.18 on 2023-05-20 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0015_alter_subject_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='classyear',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_year', to='curriculum.level', verbose_name='Уровень в IB'),
        ),
    ]
