# Generated by Django 3.2.18 on 2023-05-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0016_classyear_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classyear',
            name='level',
        ),
        migrations.AddField(
            model_name='level',
            name='class_year',
            field=models.ManyToManyField(null=True, related_name='levels', to='curriculum.ClassYear', verbose_name='Года обучения'),
        ),
    ]
