# Generated by Django 3.2.18 on 2023-05-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0017_auto_20230520_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='class_year',
            field=models.ManyToManyField(blank=True, related_name='levels', to='curriculum.ClassYear', verbose_name='Года обучения'),
        ),
    ]
