# Generated by Django 3.2.18 on 2023-05-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0018_alter_level_class_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='need_report',
            field=models.BooleanField(default=False, verbose_name='Поддержка репорта'),
        ),
    ]
