# Generated by Django 3.2.18 on 2023-05-27 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0019_subject_need_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectgroupfgos',
            options={'ordering': ['type_group', 'name_rus'], 'verbose_name': 'Предметная группа ФГОС', 'verbose_name_plural': 'Предметные группы ФГОС'},
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='type_subject',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='subjectgroupfgos',
            name='level',
        ),
        migrations.AlterField(
            model_name='classyear',
            name='program',
            field=models.CharField(choices=[('pyp', 'Primary Years Programme'), ('myp', 'Middle Years Programme'), ('dp', 'Diploma Programme'), (None, 'No program')], default=None, max_length=4, verbose_name='IB-программа'),
        ),
        migrations.AlterField(
            model_name='subjectgroupib',
            name='program',
            field=models.CharField(choices=[('pyp', 'Primary Years Programme'), ('myp', 'Middle Years Programme'), ('dp', 'Diploma Programme'), (None, 'No program')], default=None, max_length=4),
        ),
        migrations.CreateModel(
            name='EducationalProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rus', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название на рус. языке')),
                ('years', models.ManyToManyField(blank=True, related_name='edu_programs', to='curriculum.ClassYear', verbose_name='Года обучения')),
            ],
            options={
                'verbose_name': 'Образовательная программа',
                'verbose_name_plural': 'Образовательные программы',
                'ordering': ['name_rus'],
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='edu_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject', to='curriculum.educationalprogram', verbose_name='Образовательная программа'),
        ),
    ]
