# Generated by Django 3.2.18 on 2023-05-27 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0045_delete_academicplan'),
        ('curriculum', '0020_auto_20230527_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rus', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название на рус. языке')),
                ('name_short', models.CharField(blank=True, max_length=128, null=True, verbose_name='Сокращённое название')),
                ('study_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_plan', to='assess.studyyear', verbose_name='Учебный год')),
            ],
            options={
                'verbose_name': 'Образовательная программа',
                'verbose_name_plural': 'Образовательные программы',
                'ordering': ['study_year', 'name_rus'],
            },
        ),
        migrations.CreateModel(
            name='HoursSubjectInYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во часов')),
                ('academic_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='curriculum.academicplan', verbose_name='Учебный план')),
            ],
            options={
                'verbose_name': 'Учебный план',
                'verbose_name_plural': 'Учебные планы',
                'ordering': ['subject__name_rus', 'class_year'],
            },
        ),
        migrations.RemoveField(
            model_name='subject',
            name='edu_program',
        ),
        migrations.AddField(
            model_name='classyear',
            name='level',
            field=models.CharField(choices=[('noo', 'Начальная школа'), ('ooo', 'Средняя школа'), ('soo', 'Старшая школа')], default='ooo', max_length=3, verbose_name='Национальные уровни образования'),
        ),
        migrations.AddField(
            model_name='subject',
            name='level',
            field=models.CharField(choices=[('noo', 'Начальная школа'), ('ooo', 'Средняя школа'), ('soo', 'Старшая школа')], default='ooo', max_length=3, verbose_name='Уровень образования'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.CharField(choices=[('base', 'Обязательная часть'), ('base_fgos', 'Обязательная часть в соответствии с ФГОС'), ('base_ib', 'Обязательная часть в соответствии с IB'), ('extra', 'Внеурочная деятельность')], default='base', max_length=10, verbose_name='Тип предмета'),
        ),
        migrations.DeleteModel(
            name='EducationalProgram',
        ),
        migrations.AddField(
            model_name='hourssubjectinyear',
            name='class_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='curriculum.classyear', verbose_name='Год обучения'),
        ),
        migrations.AddField(
            model_name='hourssubjectinyear',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='curriculum.subject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='academicplan',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='academic_plan', through='curriculum.HoursSubjectInYear', to='curriculum.Subject', verbose_name='Предметы'),
        ),
    ]
