# Generated by Django 3.2.18 on 2023-05-27 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0021_auto_20230527_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicplan',
            options={'ordering': ['study_year', 'name_rus'], 'verbose_name': 'Учебный план', 'verbose_name_plural': 'Учебные планы'},
        ),
        migrations.AlterModelOptions(
            name='hourssubjectinyear',
            options={'ordering': ['subject__name_rus', 'class_year'], 'verbose_name': 'Учебные планы: нагрузка', 'verbose_name_plural': 'Учебные планы: нагрузка'},
        ),
        migrations.AlterField(
            model_name='hourssubjectinyear',
            name='academic_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_year', to='curriculum.academicplan', verbose_name='Учебный план'),
        ),
        migrations.AlterField(
            model_name='hourssubjectinyear',
            name='class_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_year', to='curriculum.classyear', verbose_name='Год обучения'),
        ),
        migrations.AlterField(
            model_name='hourssubjectinyear',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_year', to='curriculum.subject', verbose_name='Предмет'),
        ),
    ]
