# Generated by Django 3.2.18 on 2023-05-27 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0022_auto_20230527_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectgroupfgos',
            options={'ordering': ['type', 'name_rus'], 'verbose_name': 'Предметная группа ФГОС', 'verbose_name_plural': 'Предметные группы ФГОС'},
        ),
        migrations.RenameField(
            model_name='subjectgroupfgos',
            old_name='type_group',
            new_name='type',
        ),
    ]
