# Generated by Django 3.2.18 on 2023-05-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0023_auto_20230527_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicplan',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='hourssubjectinyear',
            name='academic_plan',
        ),
        migrations.AddField(
            model_name='academicplan',
            name='hours_subject',
            field=models.ManyToManyField(blank=True, related_name='academic_plan', to='curriculum.HoursSubjectInYear', verbose_name='Часы учебных предметов'),
        ),
    ]
