# Generated by Django 3.2.18 on 2023-05-28 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0024_auto_20230528_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicplan',
            name='hours_subject',
        ),
        migrations.AddField(
            model_name='hourssubjectinyear',
            name='academic_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_year', to='curriculum.academicplan', verbose_name='Учебный план'),
        ),
    ]
