# Generated by Django 3.2.18 on 2023-05-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0025_auto_20230528_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicplan',
            name='level',
            field=models.CharField(choices=[('noo', 'Начальная школа'), ('ooo', 'Средняя школа'), ('soo', 'Старшая школа')], default='ooo', max_length=3, verbose_name='Уровень образования'),
        ),
    ]
