# Generated by Django 3.2.18 on 2023-05-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0026_academicplan_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['type', 'group_ib', 'name_rus'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.CharField(choices=[('base', 'Обязательная часть ФГОС'), ('base_fgos', 'Обязательная часть ФГОС в IB'), ('base_ib', 'Обязательная часть IB'), ('extra', 'Внеурочная деятельность')], default='base', max_length=10, verbose_name='Тип предмета'),
        ),
    ]
