# Generated by Django 3.2.18 on 2023-05-29 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0027_auto_20230528_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hourssubjectinyear',
            options={'ordering': ['subject__name_rus'], 'verbose_name': 'Учебные планы: нагрузка', 'verbose_name_plural': 'Учебные планы: нагрузка'},
        ),
        migrations.RemoveField(
            model_name='hourssubjectinyear',
            name='class_year',
        ),
    ]
