# Generated by Django 3.2.18 on 2023-05-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0028_auto_20230529_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hourssubjectinyear',
            options={'ordering': ['subject__name_rus', 'years__year_rus'], 'verbose_name': 'Учебные планы: нагрузка', 'verbose_name_plural': 'Учебные планы: нагрузка'},
        ),
        migrations.AddField(
            model_name='hourssubjectinyear',
            name='years',
            field=models.ManyToManyField(blank=True, related_name='subject_year', to='curriculum.ClassYear', verbose_name='Года обучения'),
        ),
    ]
