# Generated by Django 3.2.18 on 2023-05-29 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0029_auto_20230529_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hourssubjectinyear',
            options={'ordering': ['subject__name_rus'], 'verbose_name': 'Учебные планы: нагрузка', 'verbose_name_plural': 'Учебные планы: нагрузка'},
        ),
        migrations.RemoveField(
            model_name='hourssubjectinyear',
            name='years',
        ),
    ]
