# Generated by Django 3.2.18 on 2023-05-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0030_auto_20230529_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourssubjectinyear',
            name='years',
            field=models.ManyToManyField(blank=True, related_name='subject_year', to='curriculum.ClassYear', verbose_name='Года обучения'),
        ),
    ]
