# Generated by Django 3.2.18 on 2023-05-31 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0031_hourssubjectinyear_years'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classyear',
            options={'ordering': ['year_rus'], 'verbose_name': 'Год обучения', 'verbose_name_plural': 'Года обучения'},
        ),
        migrations.AlterModelOptions(
            name='hourssubjectinyear',
            options={'ordering': ['subject__name_rus', 'years__year_rus'], 'verbose_name': 'Учебные планы: нагрузка', 'verbose_name_plural': 'Учебные планы: нагрузка'},
        ),
    ]
