# Generated by Django 3.2.18 on 2023-06-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0032_auto_20230531_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicplan',
            options={'ordering': ['study_year', 'name_rus'], 'verbose_name': 'ФГОС: Учебный план', 'verbose_name_plural': 'ФГОС: Учебные планы'},
        ),
        migrations.AlterModelOptions(
            name='achievementlevel',
            options={'ordering': ['objective', 'point'], 'verbose_name': 'Assessment: Уровень достижений', 'verbose_name_plural': 'Assessment: Уровни достижений'},
        ),
        migrations.AlterModelOptions(
            name='aim',
            options={'ordering': ['subject_group', 'name_eng'], 'verbose_name': 'IB: Цель', 'verbose_name_plural': 'IB: Цели'},
        ),
        migrations.AlterModelOptions(
            name='criterion',
            options={'ordering': ['subject_group', 'letter'], 'verbose_name': 'Assessment: Критерий оценивания', 'verbose_name_plural': 'Assessment: Критерии оценивания'},
        ),
        migrations.AlterModelOptions(
            name='hourssubjectinyear',
            options={'ordering': ['subject__name_rus', 'years__year_rus'], 'verbose_name': 'ФГОС: Учебные планы - нагрузка', 'verbose_name_plural': 'ФГОС: Учебные планы - нагрузка'},
        ),
        migrations.AlterModelOptions(
            name='learnerprofileib',
            options={'ordering': ['name_eng'], 'verbose_name': 'IB: Профиль студента', 'verbose_name_plural': 'IB: Профили студента'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['name_eng'], 'verbose_name': 'Assessment: Образовательный уровень', 'verbose_name_plural': 'Assessment: Образовательные уровни'},
        ),
        migrations.AlterModelOptions(
            name='objective',
            options={'ordering': ['level', 'strand'], 'verbose_name': 'Assessment: Образовательная цель', 'verbose_name_plural': 'Assessment: Образовательные цели'},
        ),
        migrations.AlterModelOptions(
            name='strand',
            options={'ordering': ['criterion', 'number', 'letter'], 'verbose_name': 'Assessment: Стрэнд', 'verbose_name_plural': 'Assessment: Стрэнды'},
        ),
        migrations.AlterModelOptions(
            name='subjectgroupfgos',
            options={'ordering': ['type', 'name_rus'], 'verbose_name': 'ФГОС: Предметная группа', 'verbose_name_plural': 'ФГОС: Предметные группы'},
        ),
        migrations.AlterModelOptions(
            name='subjectgroupib',
            options={'ordering': ['program', 'id'], 'verbose_name': 'IB: Предметная группа', 'verbose_name_plural': 'IB: Предметные группы'},
        ),
        migrations.RemoveField(
            model_name='classyear',
            name='program',
        ),
        migrations.AlterField(
            model_name='subjectgroupib',
            name='program',
            field=models.CharField(choices=[('pyp', 'Primary Years Programme'), ('myp', 'Middle Years Programme'), ('dp', 'Diploma Programme'), (None, 'No program')], default=None, max_length=4, null=True),
        ),
    ]
