# Generated by Django 4.2.4 on 2023-12-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=12, verbose_name='Letters')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'DP: Course content',
                'verbose_name_plural': 'DP: Course contents',
                'ordering': ['topic', 'letter'],
            },
        ),
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=12, verbose_name='Letters')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'DP: Course topic',
                'verbose_name_plural': 'DP: Course topics',
                'ordering': ['discipline', 'letter'],
            },
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('letter', models.CharField(max_length=1, verbose_name='Letter')),
            ],
            options={
                'verbose_name': 'DP: Criterion',
                'verbose_name_plural': 'DP: Criteria',
                'ordering': ['discipline', 'letter'],
            },
        ),
        migrations.CreateModel(
            name='DpAim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('type', models.CharField(choices=[('group', 'Group'), ('subject', 'Subject')], max_length=12, verbose_name='Тype (group or subject)')),
            ],
            options={
                'verbose_name': 'DP: Aim',
                'verbose_name_plural': 'DP: Aims',
                'ordering': ['discipline', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DpAtlDevelop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(blank=True, null=True, verbose_name='Action')),
            ],
            options={
                'verbose_name': 'DP: UnitPlan - Approaches to Learning',
                'verbose_name_plural': 'DP: UnitPlans - Approaches to Learning',
                'ordering': ['unit', 'atl'],
            },
        ),
        migrations.CreateModel(
            name='DpAtlSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_rus', models.CharField(max_length=255, null=True, verbose_name='Название на рус. языке')),
            ],
            options={
                'verbose_name': 'DP: ATL Skills',
                'verbose_name_plural': 'DP: ATL Skills',
                'ordering': ['cluster', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DpInquiryQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Inquiry Question')),
                ('type', models.CharField(choices=[('factual', 'Фактический'), ('conceptual', 'Концептуальный'), ('skills-based', 'Skills-based'), ('content-based', 'Content-based'), ('concept-based', 'Concept-based'), ('debatable', 'Дискуссионный')], default='Factual', max_length=16, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'DP: UnitPlan - Inquiry Question',
                'verbose_name_plural': 'DP: UnitPlans - Inquiry Questions',
                'ordering': ['unit', 'type', 'question'],
            },
        ),
        migrations.CreateModel(
            name='DpObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='Number')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'DP: Objective',
                'verbose_name_plural': 'DP: Objectives',
                'ordering': ['discipline', 'number'],
            },
        ),
        migrations.CreateModel(
            name='DpObjectiveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1, verbose_name='Letter')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'DP: Objectives Item',
                'verbose_name_plural': 'DP: Objectives Items',
                'ordering': ['objective', 'letter'],
            },
        ),
    ]
