# Generated by Django 4.2.4 on 2023-11-19 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dp', '0001_initial'),
        ('ibo', '0001_initial'),
        ('curriculum', '0002_initial'),
        ('general', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dpunitplanner',
            name='authors',
            field=models.ManyToManyField(related_name='dp_authors', to=settings.AUTH_USER_MODEL, verbose_name='Authors'),
        ),
        migrations.AddField(
            model_name='dpunitplanner',
            name='criteria',
            field=models.ManyToManyField(blank=True, related_name='dp_unitplans', to='dp.criterion', verbose_name='Assessment criteria'),
        ),
        migrations.AddField(
            model_name='dpunitplanner',
            name='objectives',
            field=models.ManyToManyField(blank=True, related_name='dp_unitplans', to='dp.dpobjective', verbose_name='Objectives'),
        ),
        migrations.AddField(
            model_name='dpunitplanner',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dp_unitplans', to='curriculum.subject', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='dpunitplanner',
            name='syllabus_content',
            field=models.ManyToManyField(blank=True, related_name='dp_unitplans', to='dp.coursecontent', verbose_name='Syllabus Content'),
        ),
        migrations.AddField(
            model_name='dpunitplanner',
            name='teachers',
            field=models.ManyToManyField(related_name='dp_teachers', to=settings.AUTH_USER_MODEL, verbose_name='Teachers'),
        ),
        migrations.AddField(
            model_name='dpunitplanner',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dp_unitplans', to='general.studyyear', verbose_name='Study year'),
        ),
        migrations.AddField(
            model_name='dpreflectionpost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dp_reflections', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='dpreflectionpost',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_posts', to='dp.dpunitplanner', verbose_name='Unit DP'),
        ),
        migrations.AddField(
            model_name='dpprofiledevelop',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dp_profiles', to='ibo.learnerprofile', verbose_name='IB Learner Profile'),
        ),
        migrations.AddField(
            model_name='dpprofiledevelop',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_develops', to='dp.dpunitplanner', verbose_name='Unit DP'),
        ),
        migrations.AddField(
            model_name='dpobjectiveitem',
            name='objective',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='dp.dpobjective', verbose_name='Objective'),
        ),
        migrations.AddField(
            model_name='dpobjective',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dp_objectives', to='curriculum.ibdiscipline', verbose_name='Discipline IB'),
        ),
        migrations.AddField(
            model_name='dpinquiryquestion',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_questions', to='dp.dpunitplanner', verbose_name='Unit DP'),
        ),
        migrations.AddField(
            model_name='dpatlskill',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dp_skills', to='ibo.atlcluster', verbose_name='Кластер ATL'),
        ),
        migrations.AddField(
            model_name='dpatldevelop',
            name='atl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atl_develops', to='dp.dpatlskill', verbose_name='ATL Skill'),
        ),
        migrations.AddField(
            model_name='dpatldevelop',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atl_develops', to='dp.dpunitplanner', verbose_name='Unit DP'),
        ),
        migrations.AddField(
            model_name='dpaim',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dp_aims', to='curriculum.ibdiscipline', verbose_name='Discipline IB'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dp_criteria', to='curriculum.ibdiscipline', verbose_name='Discipline IB'),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dp_topics', to='curriculum.ibdiscipline', verbose_name='Discipline IB'),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_contents', to='dp.coursetopic', verbose_name='Course Topic'),
        ),
    ]
