# Generated by Django 4.2.4 on 2023-11-24 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpprofiledevelop',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='dpprofiledevelop',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='dpreflectionpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='dpreflectionpost',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='dpunitplanner',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='dpunitplanner',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dpunitplanner',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dpunitplanner',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='dpunitplanner',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dpunitplanner',
            name='order',
        ),
        migrations.RemoveField(
            model_name='dpunitplanner',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='dpunitplanner',
            name='title',
        ),
        migrations.RemoveField(
            model_name='dpunitplanner',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='dpunitplanner',
            name='year',
        ),
    ]
