# Generated by Django 4.2.4 on 2023-11-24 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibo', '0002_unitplanerbasemodel_unitteacherroles_and_more'),
        ('dp', '0003_remove_dpprofiledevelop_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpunitplanner',
            name='unitplanerbasemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ibo.unitplanerbasemodel'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DpProfileDevelop',
        ),
        migrations.DeleteModel(
            name='DpReflectionPost',
        ),
    ]
