# Generated by Django 4.2.4 on 2023-11-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0004_dpunitplanner_unitplanerbasemodel_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpatldevelop',
            name='description',
        ),
        migrations.AddField(
            model_name='dpatldevelop',
            name='action',
            field=models.TextField(blank=True, null=True, verbose_name='Action'),
        ),
    ]
