# Generated by Django 4.2.4 on 2023-12-02 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ibo', '0001_initial'),
        ('general', '0001_initial'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Курс: Программа года',
                'verbose_name_plural': 'Курс: Программы года',
                'ordering': ['syllabus', 'year'],
            },
        ),
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='Номер')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('hours', models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во часов')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='syllabus.course', verbose_name='Курс')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_chapters', to='ibo.unitplanerbasemodel', verbose_name='Юнит')),
            ],
            options={
                'verbose_name': 'Курс: Раздел',
                'verbose_name_plural': 'Курс: Разделы',
                'ordering': ['course', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='courses/', verbose_name='Файл рабочей программы')),
                ('authors', models.ManyToManyField(related_name='author_syllabi', to=settings.AUTH_USER_MODEL, verbose_name='Авторы')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syllabi', to='curriculum.subject', verbose_name='Предмет')),
                ('years', models.ManyToManyField(blank=True, related_name='syllabi', to='general.studyyear', verbose_name='Параллели')),
            ],
            options={
                'verbose_name': 'Курс: Общая программа',
                'verbose_name_plural': 'Курс: Общие программы',
                'ordering': ['subject'],
            },
        ),
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='Номер')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('hours', models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во часов')),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='syllabus.coursechapter', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Курс: Тема',
                'verbose_name_plural': 'Курс: Темы',
                'ordering': ['chapter', 'number'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='syllabus.syllabus', verbose_name='Учебная программа'),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='general.studyyear', verbose_name='Параллель'),
        ),
    ]
