# Generated by Django 4.2.4 on 2023-11-20 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myp', '0001_initial'),
        ('general', '0001_initial'),
        ('curriculum', '0001_initial'),
        ('dp', '0001_initial'),
        ('pyp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='courses/', verbose_name='Файл рабочей программы')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='curriculum.subject', verbose_name='Предмет')),
                ('years', models.ManyToManyField(blank=True, related_name='courses', to='general.studyyear', verbose_name='Параллели')),
            ],
            options={
                'verbose_name': 'Курс предмета: полный',
                'verbose_name_plural': 'Курсы предмета: полные',
                'ordering': ['subject'],
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sections', to='syllabus.course', verbose_name='Предмет')),
                ('unit_dp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_sections', to='dp.dpunitplanner', verbose_name='Юнит DP')),
                ('unit_myp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_sections', to='myp.mypunitplanner', verbose_name='Юнит MYP')),
                ('unit_pyp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_sections', to='pyp.pypunitplanner', verbose_name='Юнит PYP')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_sections', to='general.studyyear', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Раздел курса',
                'verbose_name_plural': 'Разделы курса',
                'ordering': ['course', 'year'],
            },
        ),
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='Номер')),
                ('name', models.CharField(max_length=255, verbose_name='Тема')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('hours', models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во часов')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='syllabus.coursesection', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Тема курса',
                'verbose_name_plural': 'Темы курса',
                'ordering': ['section', 'number'],
            },
        ),
    ]
