# Generated by Django 4.2.4 on 2023-11-05 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_remove_classgroup_psychologist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во часов')),
            ],
            options={
                'verbose_name': 'Учебный план - нагрузка',
                'verbose_name_plural': 'Учебные планы - нагрузка',
                'ordering': ['subject__name', 'years__number'],
            },
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='general.department', verbose_name='Учебное подразделение'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='group_fgos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='syllabus.fgossubjectgroup', verbose_name='Предметная область в РФ'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='group_ib',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='syllabus.ibsubjectgroup', verbose_name='Предметная группа в IB'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='general.academicyear', verbose_name='Учебный год'),
        ),
        migrations.AlterField(
            model_name='teachingload',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='teaching_loads', to='general.classgroup', verbose_name='Классы'),
        ),
        migrations.AlterField(
            model_name='teachingload',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_loads', to='syllabus.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='teachingload',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_loads', to=settings.AUTH_USER_MODEL, verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='teachingload',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_loads', to='general.academicyear', verbose_name='Учебный год'),
        ),
        migrations.DeleteModel(
            name='SyllabusSubjectHours',
        ),
        migrations.AddField(
            model_name='syllabusload',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_loads', to='syllabus.subject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='syllabusload',
            name='syllabus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_loads', to='syllabus.syllabus', verbose_name='Учебный план'),
        ),
        migrations.AddField(
            model_name='syllabusload',
            name='years',
            field=models.ManyToManyField(related_name='syllabus_loads', to='general.studyyear', verbose_name='Параллель'),
        ),
    ]
