# Generated by Django 4.2.4 on 2023-09-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllabussubjecthours',
            old_name='academic_plan',
            new_name='syllabus',
        ),
        migrations.AlterField(
            model_name='subjectgroupib',
            name='program',
            field=models.CharField(choices=[('pyp', 'Primary Years Programme'), ('myp', 'Middle Years Programme'), ('dp', 'Diploma Programme'), ('None', 'No program')], default=None, max_length=4, null=True, verbose_name='Программа IB'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='name_short',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Сокращённое название'),
        ),
    ]
