# Generated by Django 4.2.4 on 2023-11-25 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_alter_subject_discipline_ib_alter_subject_dnevnik_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0001_initial'),
        ('ibo', '0002_unitplanerbasemodel_unitteacherroles_and_more'),
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='Номер')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('hours', models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во часов')),
            ],
            options={
                'verbose_name': 'Раздел курса',
                'verbose_name_plural': 'Разделы курса',
                'ordering': ['course', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='courses/', verbose_name='Файл рабочей программы')),
                ('authors', models.ManyToManyField(related_name='author_syllabi', to=settings.AUTH_USER_MODEL, verbose_name='Авторы')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syllabi', to='curriculum.subject', verbose_name='Предмет')),
                ('years', models.ManyToManyField(blank=True, related_name='syllabi', to='general.studyyear', verbose_name='Параллели')),
            ],
            options={
                'verbose_name': 'Учебный курс: программа всего курса',
                'verbose_name_plural': 'Учебный курс: программа всего курса',
                'ordering': ['subject'],
            },
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['syllabus', 'year'], 'verbose_name': 'Учебный курс: программа года', 'verbose_name_plural': 'Учебный курс: программа года'},
        ),
        migrations.AlterModelOptions(
            name='coursetopic',
            options={'ordering': ['chapter', 'number'], 'verbose_name': 'Тема курса', 'verbose_name_plural': 'Темы курса'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='file',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='course',
            name='years',
        ),
        migrations.RemoveField(
            model_name='coursetopic',
            name='section',
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='general.studyyear', verbose_name='Параллель'),
        ),
        migrations.AlterField(
            model_name='coursetopic',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.DeleteModel(
            name='CourseSection',
        ),
        migrations.AddField(
            model_name='coursechapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='syllabus.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='coursechapter',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_chapters', to='ibo.unitplanerbasemodel', verbose_name='Юнит'),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='syllabus.syllabus', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='syllabus.coursechapter', verbose_name='Раздел'),
        ),
    ]
