# Generated by Django 4.2.4 on 2023-12-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetopic',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
    ]
