# Generated by Django 4.2.4 on 2023-11-30 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibo', '0002_unitplanerbasemodel_unitteacherroles_and_more'),
        ('syllabus', '0002_coursechapter_syllabus_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='syllabus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='syllabus.syllabus', verbose_name='Учебная программа'),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_chapters', to='ibo.unitplanerbasemodel', verbose_name='Юнит'),
        ),
        migrations.AlterField(
            model_name='coursetopic',
            name='hours',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во часов'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='file',
            field=models.FileField(blank=True, upload_to='courses/', verbose_name='Файл рабочей программы'),
        ),
    ]
