# Generated by Django 4.2.4 on 2023-12-02 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0003_alter_course_syllabus_alter_coursechapter_unit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['syllabus', 'year'], 'verbose_name': 'Курс: Программа года', 'verbose_name_plural': 'Курс: Программы года'},
        ),
        migrations.AlterModelOptions(
            name='coursechapter',
            options={'ordering': ['course', 'number'], 'verbose_name': 'Курс: Раздел', 'verbose_name_plural': 'Курс: Разделы'},
        ),
        migrations.AlterModelOptions(
            name='coursetopic',
            options={'ordering': ['chapter', 'number'], 'verbose_name': 'Курс: Тема', 'verbose_name_plural': 'Курс: Темы'},
        ),
        migrations.AlterModelOptions(
            name='syllabus',
            options={'ordering': ['subject'], 'verbose_name': 'Курс: Общая программа', 'verbose_name_plural': 'Курс: Общие программы'},
        ),
    ]
