# Generated by Django 3.2.13 on 2023-02-02 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Учебный год')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Учебный год',
                'verbose_name_plural': 'Учебные года',
                'ordering': ['date_start'],
            },
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_year', models.PositiveSmallIntegerField(default=1, verbose_name='Год обучения')),
                ('letter', models.CharField(blank=True, max_length=1, null=True, verbose_name='Литера класса')),
                ('id_dnevnik', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID системы Дневник.РУ')),
                ('study_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classgroup', to='assess.studyyear', verbose_name='Учебный год')),
            ],
            options={
                'verbose_name': 'Учебный класс',
                'verbose_name_plural': 'Учебные классы',
                'ordering': ['class_year', 'letter'],
            },
        ),
    ]
