# Generated by Django 3.2.18 on 2023-03-06 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_unitplannermyp_resources'),
        ('member', '0002_alter_profileteacher_user'),
        ('assess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=1, verbose_name='Номер периода')),
                ('type', models.CharField(choices=[('trimester', 'триместр'), ('halfyear', 'полугодие')], max_length=16, verbose_name='Тип периода')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
                ('id_dnevnik', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID системы Дневник.РУ')),
                ('study_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period', to='assess.studyyear', verbose_name='Учебный год')),
            ],
            options={
                'verbose_name': 'Учебный период',
                'verbose_name_plural': 'Учебные периоды',
                'ordering': ['study_year', 'type', 'number'],
            },
        ),
        migrations.CreateModel(
            name='SummativeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название итоговой работы')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('lesson', models.PositiveSmallIntegerField(default=1, verbose_name='Номер урока')),
                ('class_groups', models.ManyToManyField(blank=True, related_name='sumwork', to='assess.ClassGroup', verbose_name='Классы')),
                ('criteria', models.ManyToManyField(blank=True, related_name='sumwork', to='curriculum.Criterion', verbose_name='Критерии оценки')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sumwork', to='assess.studyperiod', verbose_name='Период обучения')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sumwork', to='curriculum.subject', verbose_name='Учебный предмет')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sumwork', to='member.profileteacher', verbose_name='Учитель')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sumwork', to='curriculum.unitplannermyp', verbose_name='юнит')),
            ],
            options={
                'verbose_name': 'Итоговая работ',
                'verbose_name_plural': 'Итоговые работы',
                'ordering': ['period', 'subject', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WorkAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Оценка в итоговой работы',
                'verbose_name_plural': 'Оценки в итоговых работых',
                'ordering': ['work', 'student'],
            },
        ),
        migrations.CreateModel(
            name='WorkCriteriaMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.SmallIntegerField(default=0, verbose_name='Оценка по критерию')),
                ('criterion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_criterion_selected', to='curriculum.criterion', verbose_name='Критерий оценки')),
                ('work_assessment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_assess_selected', to='assess.workassessment', verbose_name='Позиция оценки в юните')),
            ],
            options={
                'verbose_name': 'Выбор критериев и оценка',
                'verbose_name_plural': 'Выборы критериев и оценка',
                'ordering': ['work_assessment', 'criterion'],
            },
        ),
        migrations.AddField(
            model_name='workassessment',
            name='criteria_marks',
            field=models.ManyToManyField(blank=True, related_name='workassess', through='assess.WorkCriteriaMark', to='curriculum.Criterion'),
        ),
        migrations.AddField(
            model_name='workassessment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workassess', to='member.profilestudent', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='workassessment',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workassess', to='assess.summativework', verbose_name='Юнит'),
        ),
    ]
