# Generated by Django 3.2.18 on 2023-03-06 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_unitplannermyp_resources'),
        ('assess', '0002_auto_20230306_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summativework',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sumwork', to='curriculum.unitplannermyp', verbose_name='Юнит'),
        ),
    ]
