# Generated by Django 3.2.18 on 2023-03-15 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_profileteacher_user'),
        ('curriculum', '0003_unitplannermyp_resources'),
        ('assess', '0003_alter_summativework_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_grade', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Средняя оценка за текущие работы')),
                ('final_grade', models.SmallIntegerField(default=0, verbose_name='Итоговая оценка')),
                ('class_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodassess', to='curriculum.classyear', verbose_name='Год обучения')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodassess', to='assess.studyperiod', verbose_name='Период')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodassess', to='member.profilestudent', verbose_name='Студент')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodassess', to='curriculum.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Журнал оценок за уч. период',
                'verbose_name_plural': 'Журналы оценок за уч. период',
                'ordering': ['period', 'student'],
            },
        ),
        migrations.AddField(
            model_name='workassessment',
            name='grade',
            field=models.SmallIntegerField(default=0, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='workcriteriamark',
            name='criterion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_criteria_mark', to='curriculum.criterion', verbose_name='Критерий оценки'),
        ),
        migrations.AlterField(
            model_name='workcriteriamark',
            name='work_assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_criteria_mark', to='assess.workassessment', verbose_name='Позиция оценки в юните'),
        ),
        migrations.CreateModel(
            name='PeriodCriteriaMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.SmallIntegerField(default=0, verbose_name='Оценка по критерию')),
                ('criterion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_criteria_mark', to='curriculum.criterion', verbose_name='Критерий оценки')),
                ('period_assessment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_criteria_mark', to='assess.periodassessment', verbose_name='Позиция оценки в уч. периоде')),
            ],
            options={
                'verbose_name': 'Оценка по выбранным критериям в периоде',
                'verbose_name_plural': 'Оценки по выбранным критериям в период',
                'ordering': ['period_assessment', 'criterion'],
            },
        ),
    ]
