# Generated by Django 3.2.18 on 2023-03-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_unitplannermyp_resources'),
        ('assess', '0004_auto_20230315_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodassessment',
            name='criteria_marks',
            field=models.ManyToManyField(blank=True, related_name='periodassess', through='assess.PeriodCriteriaMark', to='curriculum.Criterion'),
        ),
    ]
