# Generated by Django 3.2.18 on 2023-03-15 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0005_periodassessment_criteria_marks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodcriteriamark',
            options={'ordering': ['period_assess', 'criterion'], 'verbose_name': 'Оценка по выбранным критериям в периоде', 'verbose_name_plural': 'Оценки по выбранным критериям в период'},
        ),
        migrations.AlterModelOptions(
            name='workcriteriamark',
            options={'ordering': ['work_assess', 'criterion'], 'verbose_name': 'Выбор критериев и оценка', 'verbose_name_plural': 'Выборы критериев и оценка'},
        ),
        migrations.RenameField(
            model_name='periodcriteriamark',
            old_name='period_assessment',
            new_name='period_assess',
        ),
        migrations.RenameField(
            model_name='workcriteriamark',
            old_name='work_assessment',
            new_name='work_assess',
        ),
    ]
