# Generated by Django 3.2.18 on 2023-03-15 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0006_auto_20230315_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summativework',
            name='class_groups',
        ),
        migrations.RemoveField(
            model_name='summativework',
            name='date',
        ),
        migrations.RemoveField(
            model_name='summativework',
            name='lesson',
        ),
        migrations.CreateModel(
            name='WorkGroupDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('lesson', models.PositiveSmallIntegerField(default=1, verbose_name='Номер урока')),
                ('group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='workgroup', to='assess.classgroup', verbose_name='Класс')),
                ('work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workgroup', to='assess.summativework', verbose_name='Юнит')),
            ],
            options={
                'verbose_name': 'Дата итоговой работы',
                'verbose_name_plural': 'Даты итоговых работ',
                'ordering': ['work', 'group', 'date'],
            },
        ),
        migrations.AddField(
            model_name='summativework',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='sumwork', through='assess.WorkGroupDate', to='assess.ClassGroup', verbose_name='Классы'),
        ),
    ]
