# Generated by Django 3.2.18 on 2023-03-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_unitplannermyp_resources'),
        ('assess', '0007_auto_20230315_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyperiod',
            name='class_year',
            field=models.ManyToManyField(blank=True, related_name='period', to='curriculum.ClassYear', verbose_name='Год обучения'),
        ),
    ]
