# Generated by Django 3.2.18 on 2023-03-27 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_profileteacher_user'),
        ('assess', '0008_studyperiod_class_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='summativework',
            name='assessment',
            field=models.ManyToManyField(blank=True, related_name='sumwork', through='assess.WorkAssessment', to='member.ProfileStudent', verbose_name='Оценки студентов'),
        ),
        migrations.AlterField(
            model_name='workassessment',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workassess', to='assess.summativework', verbose_name='Итоговая работа'),
        ),
    ]
