# Generated by Django 3.2.18 on 2023-03-29 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_profileteacher_user'),
        ('assess', '0009_auto_20230327_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workassessment',
            options={'ordering': ['work_date', 'student'], 'verbose_name': 'Оценка в итоговой работы', 'verbose_name_plural': 'Оценки в итоговых работых'},
        ),
        migrations.RemoveField(
            model_name='summativework',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='workassessment',
            name='work',
        ),
        migrations.AddField(
            model_name='workassessment',
            name='work_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workassess', to='assess.workgroupdate', verbose_name='Дата итоговой работы'),
        ),
        migrations.AddField(
            model_name='workgroupdate',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='workgroup', through='assess.WorkAssessment', to='member.ProfileStudent', verbose_name='Оценки студентов'),
        ),
    ]
