# Generated by Django 3.2.18 on 2023-03-31 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0010_auto_20230329_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodassessment',
            old_name='class_year',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='periodassessment',
            name='criteria_marks',
        ),
        migrations.AddField(
            model_name='periodassessment',
            name='criterion_a',
            field=models.SmallIntegerField(default=None, null=True, verbose_name='Оценка по критерию A'),
        ),
        migrations.AddField(
            model_name='periodassessment',
            name='criterion_b',
            field=models.SmallIntegerField(default=None, null=True, verbose_name='Оценка по критерию B'),
        ),
        migrations.AddField(
            model_name='periodassessment',
            name='criterion_c',
            field=models.SmallIntegerField(default=None, null=True, verbose_name='Оценка по критерию C'),
        ),
        migrations.AddField(
            model_name='periodassessment',
            name='criterion_d',
            field=models.SmallIntegerField(default=None, null=True, verbose_name='Оценка по критерию D'),
        ),
        migrations.AlterField(
            model_name='workgroupdate',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workgroup', to='assess.summativework', verbose_name='Итоговая работа'),
        ),
        migrations.DeleteModel(
            name='PeriodCriteriaMark',
        ),
    ]
