# Generated by Django 3.2.18 on 2023-03-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0011_auto_20230331_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodassessment',
            name='summ_grade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Оценка за итоговые работы'),
        ),
        migrations.AlterField(
            model_name='periodassessment',
            name='form_grade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Оценка за текущие работы'),
        ),
    ]
