# Generated by Django 3.2.18 on 2023-04-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0012_auto_20230331_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodassessment',
            name='summ_grade',
            field=models.SmallIntegerField(default=None, null=True, verbose_name='Оценка за итоговые работы'),
        ),
    ]
