# Generated by Django 3.2.18 on 2023-04-11 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_remove_profilestudent_groups'),
        ('assess', '0013_alter_periodassessment_summ_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='groups', to='member.ProfileStudent', verbose_name='Год обучения'),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='study_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='assess.studyyear', verbose_name='Учебный год'),
        ),
    ]
