# Generated by Django 3.2.18 on 2023-05-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_auto_20230507_1357'),
        ('assess', '0014_auto_20230412_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroup',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='group', to='member.ProfileStudent', verbose_name='Год обучения'),
        ),
    ]
