# Generated by Django 3.2.18 on 2023-05-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0015_alter_classgroup_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classgroup',
            name='students',
        ),
    ]
