# Generated by Django 3.2.18 on 2023-05-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_remove_profilestudent_group'),
        ('assess', '0016_remove_classgroup_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='groups', to='member.ProfileStudent', verbose_name='Год обучения'),
        ),
    ]
