# Generated by Django 3.2.18 on 2023-05-07 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_remove_profilestudent_group'),
        ('assess', '0017_classgroup_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='mentor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='member.profileteacher', verbose_name='Наставник'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='support',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='member.profileteacher', verbose_name='Поддержка'),
        ),
    ]
