# Generated by Django 3.2.18 on 2023-05-07 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_remove_profilestudent_group'),
        ('assess', '0018_auto_20230507_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroup',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='member.profileteacher', verbose_name='Наставник'),
        ),
        migrations.RemoveField(
            model_name='classgroup',
            name='support',
        ),
        migrations.AddField(
            model_name='classgroup',
            name='support',
            field=models.ManyToManyField(blank=True, related_name='groups', to='member.ProfileTeacher', verbose_name='Поддержка'),
        ),
    ]
