# Generated by Django 3.2.18 on 2023-05-07 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_remove_profilestudent_group'),
        ('assess', '0019_auto_20230507_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classgroup',
            name='support',
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='member.profileteacher', verbose_name='Наставник'),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='groups', to='member.ProfileStudent', verbose_name='Студенты'),
        ),
        migrations.CreateModel(
            name='ClassEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('psychologist', 'Психолог'), ('assistant', 'Ассистент')], max_length=16, verbose_name='Роль сотрудника')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='member.profileteacher', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Сотрудник класса',
                'verbose_name_plural': 'Сотрудники классов',
                'ordering': ['role', 'employee'],
            },
        ),
    ]
