# Generated by Django 3.2.18 on 2023-05-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0020_auto_20230507_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='support',
            field=models.ManyToManyField(blank=True, related_name='groups', to='assess.ClassEmployee', verbose_name='Поддержка'),
        ),
    ]
