# Generated by Django 3.2.18 on 2023-05-08 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0021_classgroup_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=1, verbose_name='Номер периода')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
                ('study_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_period', to='assess.studyyear', verbose_name='Учебный год')),
            ],
            options={
                'verbose_name': 'Период репортов',
                'verbose_name_plural': 'Периоды репортов',
                'ordering': ['study_year', 'number'],
            },
        ),
    ]
