# Generated by Django 3.2.18 on 2023-05-08 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0017_alter_department_photo'),
        ('curriculum', '0012_alter_unitplannermyp_options'),
        ('assess', '0022_reportperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('level', models.CharField(choices=[('1', '1 уровень'), ('2', '2 уровень'), ('3', '3 уровень'), ('0', 'Без уровня')], max_length=16, verbose_name='Уровень мероприятий')),
                ('result', models.TextField(blank=True, null=True, verbose_name='Описание результатов')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'Участие в мероприятиях',
                'verbose_name_plural': 'Участия в мероприятиях',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название типа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание типа')),
            ],
            options={
                'verbose_name': 'Тип мероприятий',
                'verbose_name_plural': 'Типы мероприятий',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='periodassessment',
            options={'ordering': ['period', 'student'], 'verbose_name': 'Итоговые оценки за период', 'verbose_name_plural': 'Итоговые оценки за период'},
        ),
        migrations.AlterModelOptions(
            name='summativework',
            options={'ordering': ['period', 'subject', 'title'], 'verbose_name': 'ИР: Основаная информация', 'verbose_name_plural': 'ИР: Основная информация'},
        ),
        migrations.AlterModelOptions(
            name='workassessment',
            options={'ordering': ['work_date', 'student'], 'verbose_name': 'ИР: Журналы', 'verbose_name_plural': 'ИР: Журналы'},
        ),
        migrations.AlterModelOptions(
            name='workcriteriamark',
            options={'ordering': ['work_assess', 'criterion'], 'verbose_name': 'ИР: Оценки по критериям', 'verbose_name_plural': 'ИР: Оценки по критериям'},
        ),
        migrations.AlterModelOptions(
            name='workgroupdate',
            options={'ordering': ['work', 'group', 'date'], 'verbose_name': 'ИР: Классы', 'verbose_name_plural': 'ИР: Классы'},
        ),
        migrations.CreateModel(
            name='ReportTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст репорта')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_teacher', to='member.profileteacher', verbose_name='Автор репорта')),
                ('events', models.ManyToManyField(blank=True, related_name='report_teacher', to='assess.EventParticipation', verbose_name='Оценки студентов')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_teacher', to='assess.reportperiod', verbose_name='Период репорта')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_teacher', to='member.profilestudent', verbose_name='Студент')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_teacher', to='curriculum.subject', verbose_name='Предмет')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_teacher', to='curriculum.classyear', verbose_name='Год обучения')),
            ],
            options={
                'verbose_name': 'Репорт учителя',
                'verbose_name_plural': 'Репорты учителя',
                'ordering': ['period', 'student'],
            },
        ),
        migrations.CreateModel(
            name='ReportPsychologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст репорта')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_psycho', to='member.profileteacher', verbose_name='Автор репорта')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_psycho', to='assess.reportperiod', verbose_name='Период репорта')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_psycho', to='member.profilestudent', verbose_name='Студент')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_psycho', to='curriculum.classyear', verbose_name='Год обучения')),
            ],
            options={
                'verbose_name': 'Репорт наставника',
                'verbose_name_plural': 'Репорты наставника',
                'ordering': ['period', 'student'],
            },
        ),
        migrations.CreateModel(
            name='ReportMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст репорта')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_mentor', to='member.profileteacher', verbose_name='Автор репорта')),
                ('events', models.ManyToManyField(blank=True, related_name='report_mentor', to='assess.EventParticipation', verbose_name='Оценки студентов')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_mentor', to='assess.reportperiod', verbose_name='Период репорта')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_mentor', to='member.profilestudent', verbose_name='Студент')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_mentor', to='curriculum.classyear', verbose_name='Год обучения')),
            ],
            options={
                'verbose_name': 'Репорт наставника',
                'verbose_name_plural': 'Репорты наставника',
                'ordering': ['period', 'student'],
            },
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='assess.eventtype', verbose_name='Тип мероприятия'),
        ),
    ]
