# Generated by Django 3.2.18 on 2023-05-09 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0017_alter_department_photo'),
        ('curriculum', '0012_alter_unitplannermyp_options'),
        ('assess', '0023_auto_20230508_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportpsychologist',
            options={'ordering': ['period', 'student'], 'verbose_name': 'Репорт психолога', 'verbose_name_plural': 'Репорты психолога'},
        ),
        migrations.AlterField(
            model_name='reportmentor',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_reports', to='member.profileteacher', verbose_name='Автор репорта'),
        ),
        migrations.AlterField(
            model_name='reportmentor',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='mentor_reports', to='assess.EventParticipation', verbose_name='Оценки студентов'),
        ),
        migrations.AlterField(
            model_name='reportmentor',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_reports', to='assess.reportperiod', verbose_name='Период репорта'),
        ),
        migrations.AlterField(
            model_name='reportmentor',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_reports', to='member.profilestudent', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='reportmentor',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_reports', to='curriculum.classyear', verbose_name='Год обучения'),
        ),
        migrations.AlterField(
            model_name='reportpsychologist',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psycho_reports', to='member.profileteacher', verbose_name='Автор репорта'),
        ),
        migrations.AlterField(
            model_name='reportpsychologist',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psycho_reports', to='assess.reportperiod', verbose_name='Период репорта'),
        ),
        migrations.AlterField(
            model_name='reportpsychologist',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psycho_reports', to='member.profilestudent', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='reportpsychologist',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psycho_reports', to='curriculum.classyear', verbose_name='Год обучения'),
        ),
        migrations.AlterField(
            model_name='reportteacher',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_reports', to='member.profileteacher', verbose_name='Автор репорта'),
        ),
        migrations.AlterField(
            model_name='reportteacher',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='teacher_reports', to='assess.EventParticipation', verbose_name='Оценки студентов'),
        ),
        migrations.AlterField(
            model_name='reportteacher',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_reports', to='assess.reportperiod', verbose_name='Период репорта'),
        ),
        migrations.AlterField(
            model_name='reportteacher',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_reports', to='member.profilestudent', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='reportteacher',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_reports', to='curriculum.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='reportteacher',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_reports', to='curriculum.classyear', verbose_name='Год обучения'),
        ),
    ]
