# Generated by Django 3.2.18 on 2023-05-09 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0024_auto_20230509_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportperiod',
            name='assessment_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_period', to='assess.studyperiod', verbose_name='Оценочный период'),
        ),
        migrations.AlterField(
            model_name='reportmentor',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='mentor_reports', to='assess.EventParticipation', verbose_name='Участие в мероприятиях'),
        ),
        migrations.AlterField(
            model_name='reportteacher',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='teacher_reports', to='assess.EventParticipation', verbose_name='Участие в мероприятиях'),
        ),
    ]
