# Generated by Django 3.2.18 on 2023-05-09 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0025_auto_20230509_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipation',
            name='level',
            field=models.CharField(choices=[('1', '1 уровень'), ('2', '2 уровень'), ('3', '3 уровень'), ('0', 'Без уровня')], default='0', max_length=16, verbose_name='Уровень мероприятий'),
        ),
        migrations.AlterField(
            model_name='eventparticipation',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='assess.eventtype', verbose_name='Тип мероприятия'),
        ),
    ]
