# Generated by Django 3.2.18 on 2023-05-10 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0017_alter_department_photo'),
        ('assess', '0026_auto_20230509_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='psychologist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psycho_groups', to='member.profileteacher', verbose_name='Психолог'),
        ),
    ]
