# Generated by Django 3.2.18 on 2023-05-10 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0014_delete_academicplan'),
        ('assess', '0027_classgroup_psychologist'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во часов')),
                ('class_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='curriculum.classyear', verbose_name='Год обучения')),
                ('study_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='assess.studyyear', verbose_name='Учебный год')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='curriculum.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Учебный план',
                'verbose_name_plural': 'Учебные планы',
                'ordering': ['subject', 'class_year'],
            },
        ),
    ]
