# Generated by Django 3.2.18 on 2023-05-10 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0018_delete_workload'),
        ('curriculum', '0014_delete_academicplan'),
        ('assess', '0028_academicplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveSmallIntegerField(default=1, verbose_name='Часы')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workload', to='assess.classgroup', verbose_name='Класс')),
                ('study_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workload', to='assess.studyyear', verbose_name='Учебный год')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workload', to='curriculum.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workload', to='member.profileteacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Рабочая нагрузка',
                'verbose_name_plural': 'Рабочие нагрузки',
                'ordering': ['teacher'],
            },
        ),
    ]
