# Generated by Django 3.2.18 on 2023-05-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0029_workload'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportperiod',
            name='name',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Название периода'),
        ),
    ]
