# Generated by Django 3.2.18 on 2023-05-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0030_reportperiod_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodassessment',
            name='criterion_a',
            field=models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Оценка по критерию A'),
        ),
        migrations.AlterField(
            model_name='periodassessment',
            name='criterion_b',
            field=models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Оценка по критерию B'),
        ),
        migrations.AlterField(
            model_name='periodassessment',
            name='criterion_c',
            field=models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Оценка по критерию C'),
        ),
        migrations.AlterField(
            model_name='periodassessment',
            name='criterion_d',
            field=models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Оценка по критерию D'),
        ),
        migrations.AlterField(
            model_name='periodassessment',
            name='final_grade',
            field=models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Итоговая оценка'),
        ),
        migrations.AlterField(
            model_name='periodassessment',
            name='form_grade',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=3, verbose_name='Оценка за текущие работы'),
        ),
    ]
