# Generated by Django 3.2.18 on 2023-05-11 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0014_delete_academicplan'),
        ('assess', '0031_auto_20230511_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classgroup',
            name='support',
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='class_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='curriculum.classyear', verbose_name='Год обучения'),
        ),
        migrations.DeleteModel(
            name='ClassEmployee',
        ),
    ]
