# Generated by Django 3.2.18 on 2023-05-11 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0018_delete_workload'),
        ('assess', '0032_auto_20230511_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroup',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='member.profileteacher', verbose_name='Наставник'),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='psychologist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psycho_groups', to='member.profileteacher', verbose_name='Психолог'),
        ),
        migrations.AlterField(
            model_name='periodassessment',
            name='form_grade',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True, verbose_name='Оценка за текущие работы'),
        ),
        migrations.AlterField(
            model_name='periodassessment',
            name='summ_grade',
            field=models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Оценка за итоговые работы'),
        ),
    ]
