# Generated by Django 3.2.18 on 2023-05-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0034_auto_20230513_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportperiod',
            name='assessment_periods',
            field=models.ManyToManyField(blank=True, related_name='report_period', to='assess.StudyPeriod', verbose_name='Оценочные периоды'),
        ),
    ]
