# Generated by Django 3.2.18 on 2023-05-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0035_alter_reportperiod_assessment_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportteacher',
            name='criterion_a',
            field=models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Оценка по критерию A'),
        ),
        migrations.AddField(
            model_name='reportteacher',
            name='criterion_b',
            field=models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Оценка по критерию B'),
        ),
        migrations.AddField(
            model_name='reportteacher',
            name='criterion_c',
            field=models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Оценка по критерию C'),
        ),
        migrations.AddField(
            model_name='reportteacher',
            name='criterion_d',
            field=models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Оценка по критерию D'),
        ),
    ]
