# Generated by Django 3.2.18 on 2023-05-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0036_auto_20230513_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicplan',
            options={'ordering': ['subject__name_rus', 'class_year'], 'verbose_name': 'Учебный план', 'verbose_name_plural': 'Учебные планы'},
        ),
    ]
