# Generated by Django 3.2.18 on 2023-05-17 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0015_alter_subject_options'),
        ('assess', '0037_alter_academicplan_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_achievements', to='curriculum.achievementlevel', verbose_name='Уровень достижений')),
                ('objective', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_achievements', to='curriculum.objective', verbose_name='Предметная цель')),
            ],
            options={
                'verbose_name': 'Репорты: уровнень достижений',
                'verbose_name_plural': 'Репорты: уровни достижений',
                'ordering': ['objective'],
            },
        ),
        migrations.AddField(
            model_name='reportteacher',
            name='achievements',
            field=models.ManyToManyField(blank=True, related_name='teacher_reports', to='assess.ReportAchievements', verbose_name='Уровни достижений'),
        ),
    ]
