# Generated by Django 3.2.18 on 2023-05-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0038_auto_20230518_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpsychologist',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='psycho_reports', to='assess.EventParticipation', verbose_name='Участие в мероприятиях'),
        ),
    ]
