# Generated by Django 3.2.18 on 2023-05-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0039_reportpsychologist_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportteacher',
            name='final_grade',
            field=models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Итоговая оценка по шкале 1-5'),
        ),
        migrations.AddField(
            model_name='reportteacher',
            name='final_grade_ib',
            field=models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Итоговая оценка по шкале 1-7'),
        ),
    ]
