# Generated by Django 3.2.18 on 2023-05-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0040_auto_20230524_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportteacher',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reportteacher',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
