# Generated by Django 3.2.18 on 2023-05-26 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0041_auto_20230526_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportteacher',
            options={'ordering': ['period', 'subject__name_rus', 'author'], 'verbose_name': 'Репорт учителя', 'verbose_name_plural': 'Репорты учителя'},
        ),
    ]
