# Generated by Django 3.2.18 on 2023-05-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0042_alter_reportteacher_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportteacher',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='reportteacher',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время редактирования'),
        ),
    ]
