# Generated by Django 3.2.18 on 2023-05-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0043_auto_20230527_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workload',
            options={'ordering': ['group', 'teacher'], 'verbose_name': 'Рабочая нагрузка', 'verbose_name_plural': 'Рабочие нагрузки'},
        ),
    ]
