# Generated by Django 3.2.18 on 2023-05-27 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0044_alter_workload_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcademicPlan',
        ),
    ]
