# Generated by Django 3.2.18 on 2023-05-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0045_delete_academicplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workload',
            options={'ordering': ['study_year', 'subject', 'teacher'], 'verbose_name': 'Рабочая нагрузка', 'verbose_name_plural': 'Рабочие нагрузки'},
        ),
        migrations.RemoveField(
            model_name='workload',
            name='group',
        ),
        migrations.AddField(
            model_name='workload',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='workload', to='assess.ClassGroup', verbose_name='Классы'),
        ),
    ]
