# Generated by Django 3.2.18 on 2023-05-28 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0046_auto_20230528_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workload',
            name='groups',
        ),
    ]
