# Generated by Django 3.2.18 on 2023-05-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0047_remove_workload_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='workload',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='workload', to='assess.ClassGroup', verbose_name='Классы'),
        ),
    ]
