# Generated by Django 3.2.18 on 2023-05-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0048_workload_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmentor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время создания'),
        ),
        migrations.AddField(
            model_name='reportmentor',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время редактирования'),
        ),
        migrations.AddField(
            model_name='reportpsychologist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время создания'),
        ),
        migrations.AddField(
            model_name='reportpsychologist',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время редактирования'),
        ),
    ]
