# Generated by Django 3.2.18 on 2023-05-31 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0032_auto_20230531_1347'),
        ('assess', '0049_auto_20230531_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.SmallIntegerField(default=0, verbose_name='Балл по критерию')),
                ('criterion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_criteria', to='curriculum.criterion', verbose_name='Критерий оценки')),
                ('report_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_criteria', to='assess.reportteacher', verbose_name='Репорт учителя')),
            ],
            options={
                'verbose_name': 'Репорты: баллы за критерии',
                'verbose_name_plural': 'Репорты: баллы за критерии',
                'ordering': ['report_teacher', 'criterion'],
            },
        ),
        migrations.AddField(
            model_name='reportteacher',
            name='criteria',
            field=models.ManyToManyField(blank=True, related_name='teacher_reports', through='assess.ReportCriteria', to='curriculum.Criterion', verbose_name='Критерии '),
        ),
    ]
