# Generated by Django 3.2.18 on 2023-05-31 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0050_auto_20230531_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcriteria',
            name='mark',
            field=models.SmallIntegerField(default=None, null=True, verbose_name='Балл по критерию'),
        ),
    ]
