# Generated by Django 3.2.18 on 2023-06-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0051_alter_reportcriteria_mark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportcriteria',
            options={'ordering': ['report_teacher__student', 'criterion'], 'verbose_name': 'Репорты: баллы за критерии', 'verbose_name_plural': 'Репорты: баллы за критерии'},
        ),
        migrations.AlterModelOptions(
            name='workload',
            options={'ordering': ['study_year', 'subject', 'groups__class_year', 'teacher'], 'verbose_name': 'Рабочая нагрузка', 'verbose_name_plural': 'Рабочие нагрузки'},
        ),
        migrations.RemoveField(
            model_name='reportteacher',
            name='criterion_a',
        ),
        migrations.RemoveField(
            model_name='reportteacher',
            name='criterion_b',
        ),
        migrations.RemoveField(
            model_name='reportteacher',
            name='criterion_c',
        ),
        migrations.RemoveField(
            model_name='reportteacher',
            name='criterion_d',
        ),
        migrations.AddField(
            model_name='classgroup',
            name='program',
            field=models.CharField(choices=[('pyp', 'Primary Years Programme'), ('myp', 'Middle Years Programme'), ('dp', 'Diploma Programme'), (None, 'No program')], default=None, max_length=4, null=True, verbose_name='IB-программа'),
        ),
    ]
