# Generated by Django 4.2.4 on 2023-10-20 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(choices=[('a', 'Критерий A'), ('b', 'Критерий B'), ('c', 'Критерий C'), ('d', 'Критерий D')], max_length=1, verbose_name='Символ')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_rus', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на рус. языке')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_rus', models.TextField(blank=True, null=True, verbose_name='Описание на рус. языке')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criterion', to='syllabus.subjectgroupib', verbose_name='Предметная группа IB')),
            ],
            options={
                'verbose_name': 'Критерий оценивания',
                'verbose_name_plural': 'Критерии оценивания',
                'ordering': ['group', 'letter'],
            },
        ),
        migrations.CreateModel(
            name='EducationalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='Номер')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_rus', models.CharField(max_length=255, null=True, verbose_name='Название на рус. языке')),
                ('years', models.ManyToManyField(related_name='levels', to='general.studyyear', verbose_name='Года обучения')),
            ],
            options={
                'verbose_name': 'Образовательный уровень',
                'verbose_name_plural': 'Образовательные уровни',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='Абсолютный номер')),
                ('letter', models.PositiveIntegerField(choices=[(1, 'i'), (2, 'ii'), (3, 'iii'), (4, 'iv'), (5, 'v')], default=1, verbose_name='Метка в критерии')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_rus', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на рус. языке')),
                ('criterion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strand', to='units.criterion', verbose_name='Критерий')),
            ],
            options={
                'verbose_name': 'Стрэнд',
                'verbose_name_plural': 'Стрэнды',
                'ordering': ['criterion', 'number', 'letter'],
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Описание')),
                ('name_rus', models.CharField(max_length=255, null=True, verbose_name='Описание на рус. языке')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objective', to='units.educationallevel', verbose_name='Уровень в IB')),
                ('strand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objective', to='units.strand', verbose_name='Стрэнд')),
            ],
            options={
                'verbose_name': 'Образовательная цель',
                'verbose_name_plural': 'Образовательные цели',
                'ordering': ['level', 'strand'],
            },
        ),
    ]
