# Generated by Django 4.2.4 on 2023-10-25 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_rus', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на рус. языке')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aims', to='syllabus.ibsubjectgroup', verbose_name='Предметная группа')),
            ],
            options={
                'verbose_name': 'MYP: Цель',
                'verbose_name_plural': 'MYP: Цели',
                'ordering': ['group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AtlCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('name_rus', models.CharField(blank=True, max_length=64, null=True, verbose_name='Название на рус. языке')),
            ],
            options={
                'verbose_name': 'IB: ATL Категория',
                'verbose_name_plural': 'IB: ATL Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AtlCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('name_rus', models.CharField(blank=True, max_length=64, null=True, verbose_name='Название на рус. языке')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='units.atlcategory', verbose_name='Категория ATL')),
            ],
            options={
                'verbose_name': 'IB: ATL Кластер',
                'verbose_name_plural': 'IB: ATL Кластеры',
                'ordering': ['category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AtlSkillMyp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_rus', models.CharField(max_length=255, null=True, verbose_name='Название на рус. языке')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myp_skills', to='units.atlcluster', verbose_name='Кластер ATL')),
            ],
            options={
                'verbose_name': 'MYP: Навык ATL',
                'verbose_name_plural': 'MYP: Навыки ATL',
                'ordering': ['cluster', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(choices=[('a', 'Критерий A'), ('b', 'Критерий B'), ('c', 'Критерий C'), ('d', 'Критерий D')], max_length=1, verbose_name='Символ')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_rus', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на рус. языке')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_rus', models.TextField(blank=True, null=True, verbose_name='Описание на рус. языке')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criterion', to='syllabus.ibsubjectgroup', verbose_name='Предметная группа IB')),
            ],
            options={
                'verbose_name': 'MYP: Критерий оценивания',
                'verbose_name_plural': 'MYP: Критерии оценивания',
                'ordering': ['group', 'letter'],
            },
        ),
        migrations.CreateModel(
            name='EducationalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='Номер')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_rus', models.CharField(max_length=255, null=True, verbose_name='Название на рус. языке')),
                ('years', models.ManyToManyField(related_name='levels', to='general.studyyear', verbose_name='Года обучения')),
            ],
            options={
                'verbose_name': 'MYP: Образовательный уровень',
                'verbose_name_plural': 'MYP: Образовательные уровни',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GlobalContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('name_rus', models.CharField(max_length=64, null=True, verbose_name='Название на рус. языке')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('description_rus', models.TextField(null=True, verbose_name='Описание на рус. языке')),
            ],
            options={
                'verbose_name': 'MYP: Глобальный контекст',
                'verbose_name_plural': 'MYP: Глобальные контексты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GlobalContextExplorationToDevelop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название на англ. языке')),
                ('name_rus', models.CharField(max_length=64, null=True, verbose_name='Название на рус. языке')),
                ('global_context', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='explorations', to='units.globalcontext', verbose_name='Глобальный контекст')),
            ],
            options={
                'verbose_name': 'MYP: Глобальный контекст - Линия исследования',
                'verbose_name_plural': 'MYP: Глобальный контекст - Линии исследований',
                'ordering': ['global_context', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KeyConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('name_rus', models.CharField(max_length=32, null=True, verbose_name='Название на рус. языке')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('description_rus', models.TextField(null=True, verbose_name='Описание на рус. языке')),
            ],
            options={
                'verbose_name': 'MYP: Ключевой концепт',
                'verbose_name_plural': 'MYP: Ключевые концепты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('name_rus', models.CharField(max_length=64, null=True, verbose_name='Название на рус. языке')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('description_rus', models.TextField(null=True, verbose_name='Описание на рус. языке')),
            ],
            options={
                'verbose_name': 'IB: Профиль студента',
                'verbose_name_plural': 'IB: Профили студента',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='Абсолютный номер')),
                ('letter', models.PositiveIntegerField(choices=[('1', 'i'), ('2', 'ii'), ('3', 'iii'), ('4', 'iv'), ('5', 'v')], default=1, verbose_name='Метка в критерии')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_rus', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на рус. языке')),
                ('criterion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strand', to='units.criterion', verbose_name='Критерий')),
            ],
            options={
                'verbose_name': 'MYP: Стрэнд',
                'verbose_name_plural': 'MYP: Стрэнды',
                'ordering': ['criterion', 'number', 'letter'],
            },
        ),
        migrations.CreateModel(
            name='RelatedConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('name_rus', models.CharField(blank=True, max_length=64, null=True, verbose_name='Название на рус. языке')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_rus', models.TextField(blank=True, null=True, verbose_name='Описание на рус. языке')),
                ('disciplines', models.ManyToManyField(related_name='related_concepts', to='syllabus.ibdisciplines', verbose_name='Специальные дисциплины')),
            ],
            options={
                'verbose_name': 'MYP: Сопутствующий концепт',
                'verbose_name_plural': 'MYP: Сопутствующие концепты',
                'ordering': ['id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Описание')),
                ('name_rus', models.CharField(max_length=255, null=True, verbose_name='Описание на рус. языке')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objective', to='units.educationallevel', verbose_name='Уровень в IB')),
                ('strand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objective', to='units.strand', verbose_name='Стрэнд')),
            ],
            options={
                'verbose_name': 'MYP: Образовательная цель',
                'verbose_name_plural': 'MYP: Образовательные цели',
                'ordering': ['level', 'strand'],
            },
        ),
        migrations.CreateModel(
            name='MypUnitPlannerInterdisciplinary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название междисциплинарного юнита')),
                ('hours', models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во часов')),
                ('purpose_integration', models.TextField(blank=True, null=True, verbose_name='Цель интеграции')),
                ('conceptual_understanding', models.TextField(blank=True, null=True, verbose_name='Концептуальное понимание')),
                ('statement_inquiry', models.TextField(blank=True, null=True, verbose_name='Формулировка исследования')),
                ('tasks', models.TextField(blank=True, null=True, verbose_name='Задания')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='Введение в МДП')),
                ('learning_teaching', models.TextField(blank=True, null=True, verbose_name='Учебная деятельность')),
                ('formative_assessment', models.TextField(blank=True, null=True, verbose_name='Формирующее оценивание')),
                ('summative_assessment', models.TextField(blank=True, null=True, verbose_name='Итоговое оценивание')),
                ('differentiation', models.TextField(blank=True, null=True, verbose_name='Дифференцированный подход')),
                ('aims', models.ManyToManyField(blank=True, related_name='myp_idunitplans', to='units.aim', verbose_name='Цели')),
                ('criteria', models.ManyToManyField(blank=True, related_name='myp_idunitplans', to='units.criterion', verbose_name='Критерии оценки')),
                ('explorations', models.ManyToManyField(blank=True, related_name='myp_idunitplans', to='units.globalcontextexplorationtodevelop', verbose_name='Линии исследования')),
                ('global_context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myp_idunitplans', to='units.globalcontext', verbose_name='Глобальный контекст')),
                ('key_concepts', models.ManyToManyField(blank=True, related_name='myp_idunitplans', to='units.keyconcept', verbose_name='Ключевые концепты')),
                ('related_concepts', models.ManyToManyField(blank=True, related_name='myp_idunitplans', to='units.relatedconcept', verbose_name='Сопутствующие концепты')),
                ('strands', models.ManyToManyField(blank=True, related_name='myp_idunitplans', to='units.strand', verbose_name='Образовательные цели')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myp_idunitplans', to='general.studyyear', verbose_name='Год обучения')),
            ],
            options={
                'verbose_name': 'MYP: UnitPlan - Междисциплинарный юнит',
                'verbose_name_plural': 'MYP: UnitPlan - Междисциплинарные юниты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MypUnitPlanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Номер')),
                ('title', models.CharField(max_length=255, verbose_name='Название юнита')),
                ('hours', models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во часов')),
                ('conceptual_understanding', models.TextField(blank=True, null=True, verbose_name='Концептуальное понимание')),
                ('statement_inquiry', models.TextField(blank=True, null=True, verbose_name='Формулировка исследования')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержание (темы, знания и умения)')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='Умения')),
                ('international_mindedness', models.TextField(blank=True, null=True, verbose_name='Межкультурное понимание')),
                ('academic_integrity', models.TextField(blank=True, null=True, verbose_name='Академическая честность')),
                ('language_development', models.TextField(blank=True, null=True, verbose_name='Языковое развитие')),
                ('infocom_technology', models.TextField(blank=True, null=True, verbose_name='Использование средств ИКТ')),
                ('service_as_action', models.TextField(blank=True, null=True, verbose_name='Служение как действие')),
                ('formative_assessment', models.TextField(blank=True, null=True, verbose_name='Формирующее оценивание')),
                ('summative_assessment_task', models.TextField(blank=True, null=True, verbose_name='Итоговое оценивание (задачи)')),
                ('summative_assessment_soi', models.TextField(blank=True, null=True, verbose_name='Итоговое оценивание (взаимосвязь с SOI)')),
                ('peer_self_assessment', models.TextField(blank=True, null=True, verbose_name='Взаимное и самооценивание')),
                ('standardization_moderation', models.TextField(blank=True, null=True, verbose_name='Стандартизация и модерация')),
                ('prior_experiences', models.TextField(blank=True, null=True, verbose_name='Предыдущий опыт обучения')),
                ('learning_experiences', models.TextField(blank=True, null=True, verbose_name='Учебная деятельность')),
                ('teaching_strategies', models.TextField(blank=True, null=True, verbose_name='Стратегии преподавания')),
                ('student_expectations', models.TextField(blank=True, null=True, verbose_name='Ожидания студентов')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Обратная связь')),
                ('differentiation', models.TextField(blank=True, null=True, verbose_name='Дифференцированный подход')),
                ('resources', models.TextField(blank=True, null=True, verbose_name='Ресурсы')),
                ('aims', models.ManyToManyField(blank=True, related_name='myp_unitplans', to='units.aim', verbose_name='Цели')),
                ('authors', models.ManyToManyField(related_name='myp_unitplans', to=settings.AUTH_USER_MODEL, verbose_name='Авторы')),
                ('criteria', models.ManyToManyField(blank=True, related_name='myp_unitplans', to='units.criterion', verbose_name='Критерии оценки')),
                ('explorations', models.ManyToManyField(blank=True, related_name='myp_unitplans', to='units.globalcontextexplorationtodevelop', verbose_name='Линии исследования')),
                ('global_context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myp_unitplans', to='units.globalcontext', verbose_name='Глобальный контекст')),
                ('interdisciplinary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myp_unitplans', to='units.mypunitplannerinterdisciplinary', verbose_name='Междисциплинарный юнит')),
                ('key_concepts', models.ManyToManyField(blank=True, related_name='myp_unitplans', to='units.keyconcept', verbose_name='Ключевые концепты')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myp_unitplans', to='units.educationallevel', verbose_name='Образовательный уровень')),
                ('related_concepts', models.ManyToManyField(blank=True, related_name='myp_unitplans', to='units.relatedconcept', verbose_name='Сопутствующие концепты')),
                ('strands', models.ManyToManyField(blank=True, related_name='myp_unitplans', to='units.strand', verbose_name='Стренды предметной группы')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myp_unitplans', to='syllabus.subject', verbose_name='Предмет')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myp_unitplans', to='general.studyyear', verbose_name='Год обучения')),
            ],
            options={
                'verbose_name': 'MYP: UnitPlan - Основная информация',
                'verbose_name_plural': 'MYP: UnitPlan - Основная информация',
                'ordering': ['year', 'subject', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MypReflectionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('prior', 'Перед началом юнита'), ('during', 'Во время юнита'), ('after', 'После окончания юнита')], max_length=6, verbose_name='Тип рефлексии')),
                ('post', models.TextField(blank=True, null=True, verbose_name='Содержание рефлексии')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reflection_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор поста')),
                ('idu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_posts', to='units.mypunitplannerinterdisciplinary', verbose_name='Междисциплинарный юнит MYP')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_posts', to='units.mypunitplanner', verbose_name='Юнит MYP')),
            ],
            options={
                'verbose_name': 'UnitPlan MYP: Пост рефлексии',
                'verbose_name_plural': 'UnitPlan MYP: Посты рефлексии',
                'ordering': ['type', 'post'],
            },
        ),
        migrations.CreateModel(
            name='MypProfileDevelop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_develops', to='units.learnerprofile', verbose_name='Профиль студента')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_develops', to='units.mypunitplanner', verbose_name='Юнит MYP')),
            ],
            options={
                'verbose_name': 'MYP: UnitPlan - Развитие профиля студента',
                'verbose_name_plural': 'MYP: UnitPlan - Развитие профиля студента',
                'ordering': ['profile'],
            },
        ),
        migrations.CreateModel(
            name='MypInquiryQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Исследовательский вопрос')),
                ('type', models.CharField(choices=[('factual', 'Фактический'), ('conceptual', 'Концептуальный'), ('debatable', 'Дискуссионный')], default='Factual', max_length=12, verbose_name='Тип вопроса')),
                ('line', models.CharField(max_length=255, null=True, verbose_name='Линия исследования')),
                ('idu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_questions', to='units.mypunitplannerinterdisciplinary', verbose_name='Междисциплинарный юнит MYP')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_questions', to='units.mypunitplanner', verbose_name='Юнит MYP')),
            ],
            options={
                'verbose_name': 'MYP: UnitPlan - Исследовательский вопрос',
                'verbose_name_plural': 'MYP: UnitPlan - Исследовательские вопросы',
                'ordering': ['type', 'question'],
            },
        ),
        migrations.CreateModel(
            name='MypAtlDevelop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(blank=True, null=True, verbose_name='Описание учебных действий')),
                ('atl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atl_develops', to='units.atlskillmyp', verbose_name='Навык ATL')),
                ('strand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atl_develops', to='units.strand', verbose_name='Предметный стрэнд')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atl_develops', to='units.mypunitplanner', verbose_name='Юнит MYP')),
            ],
            options={
                'verbose_name': 'MYP: UnitPlan - Развитие ATL',
                'verbose_name_plural': 'MYP: UnitPlan - Развитие ATL',
                'ordering': ['strand'],
            },
        ),
        migrations.CreateModel(
            name='KeyConceptRecommendedSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('comment_rus', models.TextField(blank=True, null=True, verbose_name='Комментарии на рус. языке')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomended_keyconcepts', to='syllabus.ibsubjectgroup', verbose_name='Предметная группа')),
                ('key_concept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomended_subjects', to='units.keyconcept', verbose_name='Ключевой концепт')),
            ],
            options={
                'verbose_name': 'MYP: Ключевые концепции - Рекомендуемый предмет',
                'verbose_name_plural': 'MYP: Ключевые концепции - Рекомендуемые предметы',
                'ordering': ['group', 'key_concept'],
            },
        ),
        migrations.AddField(
            model_name='keyconcept',
            name='groups',
            field=models.ManyToManyField(related_name='key_concepts', through='units.KeyConceptRecommendedSubjects', to='syllabus.ibsubjectgroup', verbose_name='Рекомендуемые предметные группы'),
        ),
        migrations.CreateModel(
            name='AchievementLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True, verbose_name='Описание')),
                ('name_rus', models.TextField(blank=True, null=True, verbose_name='Описание на рус. языке')),
                ('point', models.PositiveIntegerField(default=0, verbose_name='Баллы')),
                ('objective', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievelevel', to='units.objective', verbose_name='Образовательная цель')),
            ],
            options={
                'verbose_name': 'MYP: Уровень достижений',
                'verbose_name_plural': 'MYP: Уровни достижений',
                'ordering': ['objective', 'point'],
            },
        ),
    ]
