# Generated by Django 4.2.4 on 2023-10-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pypunitplanner',
            old_name='reflections_teachers',
            new_name='reflections_teacher',
        ),
        migrations.AddField(
            model_name='pypunitplanner',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Замечания'),
        ),
    ]
