# Generated by Django 4.2.4 on 2023-10-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GlobalContextExplorationToDevelop',
            new_name='GlobalContextExploration',
        ),
        migrations.RenameModel(
            old_name='KeyConceptRecommendedSubjects',
            new_name='KeyConceptOfSubjects',
        ),
    ]
