# Generated by Django 4.2.4 on 2023-11-05 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mypinquiryquestionidu',
            options={'ordering': ['type', 'question'], 'verbose_name': 'MYP IDU: UnitPlan - Исследовательский вопрос', 'verbose_name_plural': 'MYP IDU: UnitPlans - Исследовательские вопросы'},
        ),
        migrations.AlterModelOptions(
            name='mypreflectionpostidu',
            options={'ordering': ['type', 'post'], 'verbose_name': 'MYP IDU: UnitPlan - Пост рефлексии', 'verbose_name_plural': 'MYP IDU: UnitPlans - Посты рефлексии'},
        ),
        migrations.AlterModelOptions(
            name='mypunitplannerinterdisciplinary',
            options={'ordering': ['year', 'title'], 'verbose_name': 'MYP IDU: UnitPlan - Междисциплинарный юнит', 'verbose_name_plural': 'MYP IDU: UnitPlans - Междисциплинарные юниты'},
        ),
        migrations.RemoveField(
            model_name='mypunitplanner',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='mypunitplanner',
            name='key_concepts',
        ),
        migrations.RemoveField(
            model_name='mypunitplannerinterdisciplinary',
            name='aims',
        ),
        migrations.RemoveField(
            model_name='mypunitplannerinterdisciplinary',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='mypunitplannerinterdisciplinary',
            name='formative_assessment',
        ),
        migrations.RemoveField(
            model_name='mypunitplannerinterdisciplinary',
            name='integrated_forms',
        ),
        migrations.RemoveField(
            model_name='mypunitplannerinterdisciplinary',
            name='related_concepts',
        ),
        migrations.AddField(
            model_name='mypunitplanner',
            name='key_concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myp_unitplans', to='units.mypkeyconcept', verbose_name='Ключевой концепт'),
        ),
        migrations.AddField(
            model_name='mypunitplanner',
            name='strands',
            field=models.ManyToManyField(blank=True, related_name='myp_unitplans', to='units.strand', verbose_name='Стренды'),
        ),
        migrations.AddField(
            model_name='mypunitplannerinterdisciplinary',
            name='real_world_issue',
            field=models.TextField(blank=True, null=True, verbose_name='Проблема реального мира'),
        ),
        migrations.AddField(
            model_name='mypunitplannerinterdisciplinary',
            name='strands',
            field=models.ManyToManyField(blank=True, related_name='myp_iduplans', to='units.strand', verbose_name='Предметные цели (стренды)'),
        ),
        migrations.AddField(
            model_name='mypunitplannerinterdisciplinary',
            name='synthesis',
            field=models.TextField(blank=True, null=True, verbose_name='Синтез'),
        ),
        migrations.AlterField(
            model_name='mypunitplanner',
            name='objectives',
            field=models.ManyToManyField(blank=True, related_name='myp_unitplans', to='units.mypobjective', verbose_name='Предметные цели / Критерии оценки'),
        ),
        migrations.AlterField(
            model_name='mypunitplannerinterdisciplinary',
            name='objectives',
            field=models.ManyToManyField(blank=True, related_name='myp_iduplans', to='units.mypobjective', verbose_name='Критерии оценки'),
        ),
        migrations.CreateModel(
            name='MypAtlDevelopIdu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(blank=True, null=True, verbose_name='Описание учебных действий')),
                ('atl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idu_atl_develops', to='units.mypatlskill', verbose_name='Навык ATL')),
                ('strand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idu_atl_develops', to='units.strand', verbose_name='Предметный стрэнд')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atl_develops', to='units.mypunitplannerinterdisciplinary', verbose_name='Междисциплинарный юнит MYP')),
            ],
            options={
                'verbose_name': 'MYP IDU: UnitPlan - Развитие ATL',
                'verbose_name_plural': 'MYP IDU: UnitPlans - Развитие ATL',
                'ordering': ['strand'],
            },
        ),
    ]
