# Generated by Django 4.2.4 on 2023-10-25 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_rename_globalcontextexplorationtodevelop_globalcontextexploration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mypatldevelop',
            options={'ordering': ['strand'], 'verbose_name': 'MYP: UnitPlan - Развитие ATL', 'verbose_name_plural': 'MYP: UnitPlans - Развитие ATL'},
        ),
        migrations.AlterModelOptions(
            name='mypinquiryquestion',
            options={'ordering': ['type', 'question'], 'verbose_name': 'MYP: UnitPlan - Исследовательский вопрос', 'verbose_name_plural': 'MYP: UnitPlans - Исследовательские вопросы'},
        ),
        migrations.AlterModelOptions(
            name='mypprofiledevelop',
            options={'ordering': ['profile'], 'verbose_name': 'MYP: UnitPlan - Развитие профиля студента', 'verbose_name_plural': 'MYP: UnitPlans - Развитие профиля студента'},
        ),
        migrations.AlterModelOptions(
            name='mypreflectionpost',
            options={'ordering': ['type', 'post'], 'verbose_name': 'MYP: UnitPlan - Пост рефлексии', 'verbose_name_plural': 'MYP: UnitPlans - Посты рефлексии'},
        ),
        migrations.AlterModelOptions(
            name='mypunitplanner',
            options={'ordering': ['year', 'subject', 'order', 'title'], 'verbose_name': 'MYP: UnitPlan', 'verbose_name_plural': 'MYP: UnitPlans'},
        ),
        migrations.AlterModelOptions(
            name='mypunitplannerinterdisciplinary',
            options={'ordering': ['title'], 'verbose_name': 'MYP: UnitPlan - Междисциплинарный юнит', 'verbose_name_plural': 'MYP: UnitPlans - Междисциплинарные юниты'},
        ),
    ]
