# Generated by Django 4.2.4 on 2023-11-04 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('units', '0002_rename_reflections_teachers_pypunitplanner_reflections_teacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mypunitplannerinterdisciplinary',
            old_name='purpose_integration',
            new_name='integrated_purpose',
        ),
        migrations.RemoveField(
            model_name='pypunitplanner',
            name='reflections_assessment',
        ),
        migrations.RemoveField(
            model_name='pypunitplanner',
            name='reflections_students',
        ),
        migrations.RemoveField(
            model_name='pypunitplanner',
            name='reflections_teacher',
        ),
        migrations.AddField(
            model_name='mypunitplannerinterdisciplinary',
            name='integrated_forms',
            field=models.TextField(blank=True, null=True, verbose_name='Формы интеграции'),
        ),
        migrations.AddField(
            model_name='mypunitplannerinterdisciplinary',
            name='resources',
            field=models.TextField(blank=True, null=True, verbose_name='Ресурсы'),
        ),
        migrations.CreateModel(
            name='PypUnitTeacherRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=32, null=True, verbose_name='Роль')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_roles', to='units.pypunitplanner', verbose_name='Юнит PYP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pyp_roles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'PYP: Роль автора юнита',
                'verbose_name_plural': 'PYP: Роли автора юнита',
                'ordering': ['unit', 'user', 'role'],
            },
        ),
        migrations.CreateModel(
            name='PypReflectionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('teacher', 'Рефлексия учителя'), ('students', 'Рефлексия студентов'), ('assessment', 'Рефлексия оценивания')], max_length=10, verbose_name='Тип рефлексии')),
                ('post', models.TextField(blank=True, null=True, verbose_name='Содержание рефлексии')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pyp_reflections', to=settings.AUTH_USER_MODEL, verbose_name='Автор поста')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pyp_reflections', to='units.pypunitplanner', verbose_name='Юнит PYP')),
            ],
            options={
                'verbose_name': 'PYP: UnitPlan - Пост рефлексии',
                'verbose_name_plural': 'PYP: UnitPlans - Посты рефлексии',
                'ordering': ['type', 'post'],
            },
        ),
        migrations.AlterField(
            model_name='pypunitplanner',
            name='teachers',
            field=models.ManyToManyField(related_name='pyp_unitplans', through='units.PypUnitTeacherRoles', to=settings.AUTH_USER_MODEL, verbose_name='Учителя'),
        ),
    ]
