# Generated by Django 4.2.4 on 2023-11-04 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('units', '0003_rename_purpose_integration_mypunitplannerinterdisciplinary_integrated_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pypunitteacherroles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pyp_unitroles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
