# Generated by Django 4.2.4 on 2023-10-25 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        ('syllabus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('units', '0003_alter_mypatldevelop_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PypAtlGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('name_rus', models.CharField(blank=True, max_length=64, null=True, verbose_name='Название на рус. языке')),
            ],
            options={
                'verbose_name': 'PYP: ATL группа',
                'verbose_name_plural': 'PYP: ATL группы',
                'ordering': ['cluster', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PypKeyConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('name_rus', models.CharField(max_length=32, null=True, verbose_name='Название на рус. языке')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('description_rus', models.TextField(null=True, verbose_name='Описание на рус. языке')),
            ],
            options={
                'verbose_name': 'MYP: Ключевой концепт',
                'verbose_name_plural': 'MYP: Ключевые концепты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransdisciplinaryTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_rus', models.CharField(max_length=64, null=True, verbose_name='Название на рус. языке')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('description_rus', models.TextField(null=True, verbose_name='Описание на рус. языке')),
            ],
            options={
                'verbose_name': 'PYP: Трансдисциплинарная тема',
                'verbose_name_plural': 'PYP: Трансдисциплинарные темы',
                'ordering': ['name'],
            },
        ),
        migrations.RenameModel(
            old_name='AtlSkillMyp',
            new_name='MypAtlSkill',
        ),
        migrations.AlterModelOptions(
            name='atlcategory',
            options={'ordering': ['id'], 'verbose_name': 'IB: ATL категория', 'verbose_name_plural': 'IB: ATL категории'},
        ),
        migrations.AlterModelOptions(
            name='atlcluster',
            options={'ordering': ['category', 'id'], 'verbose_name': 'IB: ATL кластер', 'verbose_name_plural': 'IB: ATL кластеры'},
        ),
        migrations.AlterModelOptions(
            name='keyconcept',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mypunitplannerinterdisciplinary',
            options={'ordering': ['year', 'title'], 'verbose_name': 'MYP: UnitPlan - Междисциплинарный юнит', 'verbose_name_plural': 'MYP: UnitPlans - Междисциплинарные юниты'},
        ),
        migrations.RemoveField(
            model_name='keyconcept',
            name='groups',
        ),
        migrations.RenameModel(
            old_name='KeyConceptOfSubjects',
            new_name='MypKeyConceptOfSubjects',
        ),
        migrations.CreateModel(
            name='PypUnitPlanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название юнита')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Номер')),
                ('hours', models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во часов')),
                ('central_idea', models.TextField(blank=True, null=True, verbose_name='Центральная идея')),
                ('action', models.TextField(blank=True, null=True, verbose_name='Действия')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pyp_unitplans', to='general.studyyear', verbose_name='Год обучения')),
                ('key_concepts', models.ManyToManyField(blank=True, related_name='pyp_unitplans', to='units.pypkeyconcept', verbose_name='Ключевые концепты')),
                ('teachers', models.ManyToManyField(related_name='pyp_unitplans', to=settings.AUTH_USER_MODEL, verbose_name='Учителя')),
                ('transdisciplinary_theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pyp_unitplans', to='units.transdisciplinarytheme', verbose_name='Трансдисциплинарная тема')),
            ],
            options={
                'verbose_name': 'PYP: UnitPlan',
                'verbose_name_plural': 'PYP: UnitPlans',
                'ordering': ['grade', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PypRelatedConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_concepts', to='units.pypunitplanner', verbose_name='Юнит PYP')),
            ],
            options={
                'verbose_name': 'PYP: UnitPlan - Сопутствующее понятие',
                'verbose_name_plural': 'PYP: UnitPlans - Сопутствующие понятия',
                'ordering': ['unit', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PypProfileAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_attributes', to='units.learnerprofile', verbose_name='Профиль студента')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_attributes', to='units.pypunitplanner', verbose_name='Юнит PYP')),
            ],
            options={
                'verbose_name': 'PYP: UnitPlan - Развитие профиля студента',
                'verbose_name_plural': 'PYP: UnitPlans - Развитие профиля студента',
                'ordering': ['unit', 'profile'],
            },
        ),
        migrations.CreateModel(
            name='PypLinesOfInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Линия исследования')),
                ('key_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_lines', to='units.pypkeyconcept', verbose_name='Ключевой концепт')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_lines', to='units.pypunitplanner', verbose_name='Юнит PYP')),
            ],
            options={
                'verbose_name': 'PYP: UnitPlan - Линия исследования',
                'verbose_name_plural': 'PYP: UnitPlans - Линии исследования',
                'ordering': ['unit', 'key_concept', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PypAtlSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_rus', models.CharField(max_length=255, null=True, verbose_name='Название на рус. языке')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pyp_skills', to='units.pypatlgroup', verbose_name='Группа ATL')),
            ],
            options={
                'verbose_name': 'PYP: ATL навык',
                'verbose_name_plural': 'PYP: ATL навыки',
                'ordering': ['group', 'name'],
            },
        ),
        migrations.AddField(
            model_name='pypatlgroup',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pyp_groups', to='units.atlcluster', verbose_name='Кластер ATL'),
        ),
        migrations.CreateModel(
            name='PypAtlDevelop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(blank=True, null=True, verbose_name='Описание учебных действий')),
                ('atl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atl_develops', to='units.pypatlskill', verbose_name='Навык ATL')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atl_develops', to='units.pypunitplanner', verbose_name='Юнит PYP')),
            ],
            options={
                'verbose_name': 'PYP: UnitPlan - Развитие ATL',
                'verbose_name_plural': 'PYP: UnitPlans - Развитие ATL',
                'ordering': ['unit', 'atl'],
            },
        ),
        migrations.CreateModel(
            name='MypKeyConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('name_rus', models.CharField(max_length=32, null=True, verbose_name='Название на рус. языке')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('description_rus', models.TextField(null=True, verbose_name='Описание на рус. языке')),
                ('groups', models.ManyToManyField(related_name='key_concepts', through='units.MypKeyConceptOfSubjects', to='syllabus.ibsubjectgroup', verbose_name='Рекомендуемые предметные группы')),
            ],
            options={
                'verbose_name': 'MYP: Ключевой концепт',
                'verbose_name_plural': 'MYP: Ключевые концепты',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='mypkeyconceptofsubjects',
            name='key_concept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomended_subjects', to='units.mypkeyconcept', verbose_name='Ключевой концепт'),
        ),
        migrations.AlterField(
            model_name='mypunitplanner',
            name='key_concepts',
            field=models.ManyToManyField(blank=True, related_name='myp_unitplans', to='units.mypkeyconcept', verbose_name='Ключевые концепты'),
        ),
        migrations.AlterField(
            model_name='mypunitplannerinterdisciplinary',
            name='key_concepts',
            field=models.ManyToManyField(blank=True, related_name='myp_idunitplans', to='units.mypkeyconcept', verbose_name='Ключевые концепты'),
        ),
    ]
