# Generated by Django 4.2.4 on 2023-10-25 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_pypatlgroup_pypkeyconcept_transdisciplinarytheme_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeyConcept',
        ),
    ]
