# Generated by Django 4.2.4 on 2023-10-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_delete_keyconcept'),
    ]

    operations = [
        migrations.AddField(
            model_name='pypunitplanner',
            name='conncetions',
            field=models.TextField(blank=True, null=True, verbose_name='Трансдисциплинарные и прошлые связи'),
        ),
        migrations.AddField(
            model_name='pypunitplanner',
            name='engaging_learning',
            field=models.TextField(blank=True, null=True, verbose_name='Создание вовлечённого обучения'),
        ),
        migrations.AddField(
            model_name='pypunitplanner',
            name='learning_goals',
            field=models.TextField(blank=True, null=True, verbose_name='Цели обучения и критерии успеха'),
        ),
        migrations.AddField(
            model_name='pypunitplanner',
            name='ongoing_assessment',
            field=models.TextField(blank=True, null=True, verbose_name='Текущее оценивание'),
        ),
        migrations.AddField(
            model_name='pypunitplanner',
            name='peer_self_assessment',
            field=models.TextField(blank=True, null=True, verbose_name='Самооценка учащихся и отзывы сверстников'),
        ),
        migrations.AddField(
            model_name='pypunitplanner',
            name='prior_learning',
            field=models.TextField(blank=True, null=True, verbose_name='Предшествующий опыт'),
        ),
        migrations.AddField(
            model_name='pypunitplanner',
            name='questions_all',
            field=models.TextField(blank=True, null=True, verbose_name='Вопросы учителя и студента'),
        ),
        migrations.AddField(
            model_name='pypunitplanner',
            name='questions_student',
            field=models.TextField(blank=True, null=True, verbose_name='Вопросы студента'),
        ),
        migrations.AddField(
            model_name='pypunitplanner',
            name='questions_teacher',
            field=models.TextField(blank=True, null=True, verbose_name='Вопросы учителя'),
        ),
        migrations.AddField(
            model_name='pypunitplanner',
            name='reflections_additional',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная рефлексия по предметам'),
        ),
        migrations.AddField(
            model_name='pypunitplanner',
            name='reflections_assessment',
            field=models.TextField(blank=True, null=True, verbose_name='Рефлексия оценивания'),
        ),
        migrations.AddField(
            model_name='pypunitplanner',
            name='reflections_initial',
            field=models.TextField(blank=True, null=True, verbose_name='Начальная рефлексия'),
        ),
        migrations.AddField(
            model_name='pypunitplanner',
            name='reflections_ongoing',
            field=models.TextField(blank=True, null=True, verbose_name='Текущая рефлексия для всех учителей'),
        ),
        migrations.AddField(
            model_name='pypunitplanner',
            name='reflections_students',
            field=models.TextField(blank=True, null=True, verbose_name='Рефлексия студентов'),
        ),
        migrations.AddField(
            model_name='pypunitplanner',
            name='reflections_teachers',
            field=models.TextField(blank=True, null=True, verbose_name='Рефлексия учителя'),
        ),
        migrations.AddField(
            model_name='pypunitplanner',
            name='resources',
            field=models.TextField(blank=True, null=True, verbose_name='Использование ресурсов'),
        ),
        migrations.AddField(
            model_name='pypunitplanner',
            name='supporting_agency',
            field=models.TextField(blank=True, null=True, verbose_name='Поддержание свободного волеизъявления студентов'),
        ),
    ]
